# Generated by Django 4.2.4 on 2026-02-16 22:44

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(default='MEDICAL_DOCUMENT_VERSION', max_length=50)),
                ('aggregate_id', models.UUIDField()),
                ('event_type', models.CharField(choices=[('GENERATE_PDF', 'Generate PDF'), ('HIDRIVE_UPLOAD', 'HiDrive upload'), ('SMS_SEND', 'SMS send')], max_length=30)),
                ('payload_schema_version', models.SmallIntegerField(default=1)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead letter')], default='PENDING', max_length=20)),
                ('retry_count', models.SmallIntegerField(default=0)),
                ('max_retries', models.SmallIntegerField(default=10)),
                ('available_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medical_document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='medical.medicaldocumentversion')),
            ],
            options={
                'db_table': 'outbox_event',
                'indexes': [models.Index(fields=['status', 'available_at'], name='outbox_even_status_426fab_idx'), models.Index(fields=['event_type', 'status', 'retry_count', 'available_at', 'payload_schema_version'], name='outbox_even_event_t_1d90d4_idx'), models.Index(fields=['medical_document_version', '-created_at'], name='outbox_even_medical_ca0181_idx'), models.Index(condition=models.Q(('status__in', ['PENDING', 'FAILED'])), fields=['status', 'available_at'], name='outbox_pend_fail_idx'), django.contrib.postgres.indexes.GinIndex(fields=['payload'], name='outbox_payload_gin_idx', opclasses=['jsonb_path_ops'])],
            },
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.UniqueConstraint(fields=('medical_document_version', 'event_type'), name='outbox_event_unique_per_type'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('retry_count__gte', 0), ('max_retries__gt', 0), ('retry_count__lte', models.F('max_retries'))), name='outbox_event_retry_bounds'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('aggregate_type', 'MEDICAL_DOCUMENT_VERSION')), name='outbox_event_aggregate_type_guard'),
        ),
        migrations.AddConstraint(
            model_name='outboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('aggregate_id', models.F('medical_document_version_id'))), name='outbox_event_aggregate_id_guard'),
        ),
    ]
