# Generated by Django 6.0.2 on 2026-03-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outbox', '0002_outbox_pend_fail_order_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outboxevent',
            name='aggregate_type',
            field=models.CharField(default='MEDICAL_DOCUMENT_VERSION', max_length=50, verbose_name='Aggregate type'),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='available_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Available at'),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error message'),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='event_type',
            field=models.CharField(choices=[('GENERATE_PDF', 'Generate PDF'), ('HIDRIVE_UPLOAD', 'HiDrive upload'), ('SMS_SEND', 'SMS send')], max_length=30, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Locked at'),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='max_retries',
            field=models.SmallIntegerField(default=10, verbose_name='Max retries'),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='payload',
            field=models.JSONField(verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='payload_schema_version',
            field=models.SmallIntegerField(default=1, verbose_name='Payload schema version'),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processed at'),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='retry_count',
            field=models.SmallIntegerField(default=0, verbose_name='Retry count'),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead letter')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
    ]
