# Generated by Django 6.0.4 on 2026-04-15 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_alter_externalpdfattachment_options_and_more'),
        ('outbox', '0003_alter_outboxevent_aggregate_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outboxevent',
            options={'verbose_name': 'Outbox event', 'verbose_name_plural': 'Outbox events'},
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='aggregate_id',
            field=models.UUIDField(verbose_name='Aggregate ID'),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='medical_document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='medical.medicaldocumentversion', verbose_name='Medical document version'),
        ),
        migrations.AlterField(
            model_name='outboxevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
