# Generated by Django 4.2.4 on 2026-02-16 22:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnamnesisOptionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('option_text_de', models.TextField()),
                ('option_text_en', models.TextField()),
                ('display_order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'anamnesis_option_definition',
            },
        ),
        migrations.CreateModel(
            name='AnamnesisQuestionDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=80)),
                ('version', models.IntegerField(default=1)),
                ('question_text_de', models.TextField()),
                ('question_text_en', models.TextField()),
                ('answer_type', models.CharField(choices=[('SINGLE_CHOICE', 'Single choice'), ('MULTI_CHOICE', 'Multi choice'), ('BOOLEAN', 'Boolean'), ('TEXT_OPTIONAL', 'Text optional')], default='SINGLE_CHOICE', max_length=30)),
                ('is_required', models.BooleanField(default=True)),
                ('display_order', models.SmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(auto_now_add=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'anamnesis_question_definition',
            },
        ),
        migrations.CreateModel(
            name='ConsentDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=60)),
                ('version', models.IntegerField()),
                ('title_de', models.CharField(max_length=200)),
                ('content_de', models.TextField()),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.SmallIntegerField(default=0)),
                ('effective_from', models.DateField(auto_now_add=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'consent_definition',
            },
        ),
        migrations.CreateModel(
            name='PatientIntakeConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accepted', models.BooleanField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_intake_consent',
            },
        ),
        migrations.CreateModel(
            name='PatientIntakeForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('form_status', models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted')], default='IN_PROGRESS', max_length=20)),
                ('body_map_schema_version', models.SmallIntegerField(default=1)),
                ('body_map_data', models.JSONField(default=list)),
                ('anamnesis_schema_version', models.SmallIntegerField(default=1)),
                ('anamnesis_payload', models.JSONField(default=dict)),
                ('signature_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('signature_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patient_intake_form',
            },
        ),
    ]
