# Generated by Django 4.2.4 on 2026-02-16 22:44

import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reception', '0001_initial'),
        ('intake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientintakeform',
            name='queue_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake_form', to='reception.queueentry'),
        ),
        migrations.AddField(
            model_name='patientintakeform',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='intake_form', to='reception.patientformsession'),
        ),
        migrations.AddField(
            model_name='patientintakeconsent',
            name='consent_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='intake_consents', to='intake.consentdefinition'),
        ),
        migrations.AddField(
            model_name='patientintakeconsent',
            name='intake_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='intake.patientintakeform'),
        ),
        migrations.AddIndex(
            model_name='consentdefinition',
            index=models.Index(fields=['code', 'is_active', '-effective_from'], name='consent_def_code_f034bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='consentdefinition',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='consent_definition_unique'),
        ),
        migrations.AddConstraint(
            model_name='consentdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='consent_effective_to_after_from'),
        ),
        migrations.AddIndex(
            model_name='anamnesisquestiondefinition',
            index=models.Index(fields=['code', 'is_active', '-effective_from'], name='anamnesis_q_code_d3299c_idx'),
        ),
        migrations.AddConstraint(
            model_name='anamnesisquestiondefinition',
            constraint=models.UniqueConstraint(fields=('code', 'version'), name='anamnesis_question_definition_unique'),
        ),
        migrations.AddConstraint(
            model_name='anamnesisquestiondefinition',
            constraint=models.CheckConstraint(condition=models.Q(('effective_to__isnull', True), ('effective_to__gte', models.F('effective_from')), _connector='OR'), name='anamnesis_question_effective_to_after_from'),
        ),
        migrations.AddField(
            model_name='anamnesisoptiondefinition',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='intake.anamnesisquestiondefinition'),
        ),
        migrations.AddIndex(
            model_name='patientintakeform',
            index=models.Index(fields=['form_status', 'submitted_at'], name='patient_int_form_st_40a9bf_idx'),
        ),
        migrations.AddIndex(
            model_name='patientintakeform',
            index=django.contrib.postgres.indexes.GinIndex(fields=['body_map_data'], name='intake_body_map_gin_idx', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddIndex(
            model_name='patientintakeform',
            index=django.contrib.postgres.indexes.GinIndex(fields=['anamnesis_payload'], name='intake_anamnesis_gin_idx', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddConstraint(
            model_name='patientintakeform',
            constraint=models.CheckConstraint(condition=models.Q(('form_status', 'IN_PROGRESS'), models.Q(('submitted_at__isnull', False), ('signature_file_path__isnull', False)), _connector='OR'), name='intake_submitted_requires_signature'),
        ),
        migrations.AddIndex(
            model_name='patientintakeconsent',
            index=models.Index(fields=['intake_form', 'accepted'], name='patient_int_intake__727d90_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientintakeconsent',
            constraint=models.UniqueConstraint(fields=('intake_form', 'consent_definition'), name='intake_consent_unique'),
        ),
        migrations.AddConstraint(
            model_name='patientintakeconsent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted', True), ('accepted_at__isnull', False)), models.Q(('accepted', False), ('accepted_at__isnull', True)), _connector='OR'), name='intake_consent_accepted_time'),
        ),
        migrations.AddIndex(
            model_name='anamnesisoptiondefinition',
            index=models.Index(fields=['question', 'is_active', 'display_order'], name='anamnesis_o_questio_7a9cdf_idx'),
        ),
        migrations.AddConstraint(
            model_name='anamnesisoptiondefinition',
            constraint=models.UniqueConstraint(fields=('question', 'code'), name='anamnesis_option_definition_unique'),
        ),
    ]
