# Generated by Django 6.0.2 on 2026-02-28 17:00

import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0010_fill_polish_from_german'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntakeDocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.IntegerField()),
                ('form_locale', models.CharField(max_length=10)),
                ('snapshot_payload', models.JSONField(default=dict)),
                ('pdf_generation_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('pdf_local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('pdf_checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('hidrive_path', models.CharField(blank=True, max_length=500, null=True)),
                ('hidrive_sent', models.BooleanField(default=False)),
                ('hidrive_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intake_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_versions', to='intake.patientintakeform')),
            ],
            options={
                'db_table': 'intake_document_version',
            },
        ),
        migrations.CreateModel(
            name='IntakeOutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aggregate_type', models.CharField(default='INTAKE_DOCUMENT_VERSION', max_length=50)),
                ('aggregate_id', models.UUIDField()),
                ('event_type', models.CharField(choices=[('GENERATE_INTAKE_PDF', 'Generate intake PDF'), ('HIDRIVE_UPLOAD_INTAKE_PDF', 'HiDrive upload intake PDF')], max_length=40)),
                ('payload_schema_version', models.SmallIntegerField(default=1)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead letter')], default='PENDING', max_length=20)),
                ('retry_count', models.SmallIntegerField(default=0)),
                ('max_retries', models.SmallIntegerField(default=10)),
                ('available_at', models.DateTimeField(auto_now_add=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intake_document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='intake.intakedocumentversion')),
            ],
            options={
                'db_table': 'intake_outbox_event',
            },
        ),
        migrations.AddIndex(
            model_name='intakedocumentversion',
            index=models.Index(fields=['intake_form', '-version_no'], name='intake_docu_intake__a5574a_idx'),
        ),
        migrations.AddIndex(
            model_name='intakedocumentversion',
            index=models.Index(fields=['pdf_generation_status', '-created_at'], name='intake_docu_pdf_gen_db64c2_idx'),
        ),
        migrations.AddIndex(
            model_name='intakedocumentversion',
            index=models.Index(fields=['hidrive_sent', '-created_at'], name='intake_docu_hidrive_0905e5_idx'),
        ),
        migrations.AddIndex(
            model_name='intakedocumentversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['snapshot_payload'], name='intake_snap_gin_idx', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddConstraint(
            model_name='intakedocumentversion',
            constraint=models.UniqueConstraint(fields=('intake_form', 'version_no'), name='intake_document_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='intakedocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gt', 0)), name='intake_document_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='intakedocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('form_locale__regex', '^(de|en|pl)(-[A-Z]{2})?$')), name='intake_document_locale_format'),
        ),
        migrations.AddConstraint(
            model_name='intakedocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pdf_generation_status', 'COMPLETED'), ('pdf_local_path__isnull', False)), models.Q(('pdf_generation_status', 'COMPLETED'), _negated=True), _connector='OR'), name='intake_document_pdf_completed_requires_path'),
        ),
        migrations.AddConstraint(
            model_name='intakedocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('hidrive_sent', False), models.Q(('hidrive_sent', True), ('hidrive_sent_at__isnull', False)), _connector='OR'), name='intake_document_hidrive_sent_requires_time'),
        ),
        migrations.AddIndex(
            model_name='intakeoutboxevent',
            index=models.Index(fields=['status', 'available_at'], name='intake_outb_status_ee08ae_idx'),
        ),
        migrations.AddIndex(
            model_name='intakeoutboxevent',
            index=models.Index(fields=['event_type', 'status', 'retry_count', 'available_at', 'payload_schema_version'], name='intake_outb_event_t_b7266a_idx'),
        ),
        migrations.AddIndex(
            model_name='intakeoutboxevent',
            index=models.Index(fields=['intake_document_version', '-created_at'], name='intake_outb_intake__675381_idx'),
        ),
        migrations.AddIndex(
            model_name='intakeoutboxevent',
            index=models.Index(condition=models.Q(('status__in', ['PENDING', 'FAILED'])), fields=['status', 'available_at'], name='intake_outbox_pend_fail_idx'),
        ),
        migrations.AddIndex(
            model_name='intakeoutboxevent',
            index=models.Index(condition=models.Q(('status__in', ['PENDING', 'FAILED'])), fields=['available_at', 'created_at'], name='intake_outbox_pf_order_idx'),
        ),
        migrations.AddIndex(
            model_name='intakeoutboxevent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['payload'], name='intake_outbox_payload_gin_idx', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddConstraint(
            model_name='intakeoutboxevent',
            constraint=models.UniqueConstraint(fields=('intake_document_version', 'event_type'), name='intake_outbox_event_unique_per_type'),
        ),
        migrations.AddConstraint(
            model_name='intakeoutboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('retry_count__gte', 0), ('max_retries__gt', 0), ('retry_count__lte', models.F('max_retries'))), name='intake_outbox_event_retry_bounds'),
        ),
        migrations.AddConstraint(
            model_name='intakeoutboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('aggregate_type', 'INTAKE_DOCUMENT_VERSION')), name='intake_outbox_event_aggregate_type_guard'),
        ),
        migrations.AddConstraint(
            model_name='intakeoutboxevent',
            constraint=models.CheckConstraint(condition=models.Q(('aggregate_id', models.F('intake_document_version_id'))), name='intake_outbox_event_aggregate_id_guard'),
        ),
    ]
