# Generated by Django 6.0.2 on 2026-03-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0018_update_contact_method_prompt_multiselect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesisoptiondefinition',
            name='code',
            field=models.CharField(max_length=80, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='anamnesisoptiondefinition',
            name='display_order',
            field=models.SmallIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='anamnesisoptiondefinition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='anamnesisoptiondefinition',
            name='option_text_de',
            field=models.TextField(verbose_name='Option text de'),
        ),
        migrations.AlterField(
            model_name='anamnesisoptiondefinition',
            name='option_text_en',
            field=models.TextField(verbose_name='Option text en'),
        ),
        migrations.AlterField(
            model_name='anamnesisoptiondefinition',
            name='option_text_pl',
            field=models.TextField(blank=True, default='', verbose_name='Option text pl'),
        ),
        migrations.AlterField(
            model_name='anamnesisquestiondefinition',
            name='code',
            field=models.CharField(max_length=80, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='anamnesisquestiondefinition',
            name='display_order',
            field=models.SmallIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='anamnesisquestiondefinition',
            name='effective_from',
            field=models.DateField(auto_now_add=True, verbose_name='Effective from'),
        ),
        migrations.AlterField(
            model_name='anamnesisquestiondefinition',
            name='effective_to',
            field=models.DateField(blank=True, null=True, verbose_name='Effective to'),
        ),
        migrations.AlterField(
            model_name='anamnesisquestiondefinition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='anamnesisquestiondefinition',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Is required'),
        ),
        migrations.AlterField(
            model_name='anamnesisquestiondefinition',
            name='question_text_de',
            field=models.TextField(verbose_name='Question text de'),
        ),
        migrations.AlterField(
            model_name='anamnesisquestiondefinition',
            name='question_text_en',
            field=models.TextField(verbose_name='Question text en'),
        ),
        migrations.AlterField(
            model_name='anamnesisquestiondefinition',
            name='question_text_pl',
            field=models.TextField(blank=True, default='', verbose_name='Question text pl'),
        ),
        migrations.AlterField(
            model_name='anamnesisquestiondefinition',
            name='version',
            field=models.IntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='code',
            field=models.CharField(max_length=60, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='content_de',
            field=models.TextField(verbose_name='Content de'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='content_en',
            field=models.TextField(blank=True, default='', verbose_name='Content en'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='content_pl',
            field=models.TextField(blank=True, default='', verbose_name='Content pl'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='display_order',
            field=models.SmallIntegerField(default=0, verbose_name='Display order'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='effective_from',
            field=models.DateField(auto_now_add=True, verbose_name='Effective from'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='effective_to',
            field=models.DateField(blank=True, null=True, verbose_name='Effective to'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='is_required',
            field=models.BooleanField(default=True, verbose_name='Is required'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='title_de',
            field=models.CharField(max_length=200, verbose_name='Title de'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title en'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='title_pl',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title pl'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='version',
            field=models.IntegerField(verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='intakedocumentversion',
            name='form_locale',
            field=models.CharField(max_length=10, verbose_name='Form locale'),
        ),
        migrations.AlterField(
            model_name='intakedocumentversion',
            name='hidrive_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Hidrive path'),
        ),
        migrations.AlterField(
            model_name='intakedocumentversion',
            name='hidrive_sent',
            field=models.BooleanField(default=False, verbose_name='Hidrive sent'),
        ),
        migrations.AlterField(
            model_name='intakedocumentversion',
            name='hidrive_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hidrive sent at'),
        ),
        migrations.AlterField(
            model_name='intakedocumentversion',
            name='pdf_checksum_sha256',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Pdf checksum sha256'),
        ),
        migrations.AlterField(
            model_name='intakedocumentversion',
            name='pdf_local_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Pdf local path'),
        ),
        migrations.AlterField(
            model_name='intakedocumentversion',
            name='snapshot_payload',
            field=models.JSONField(default=dict, verbose_name='Snapshot payload'),
        ),
        migrations.AlterField(
            model_name='intakedocumentversion',
            name='version_no',
            field=models.IntegerField(verbose_name='Version no'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='aggregate_type',
            field=models.CharField(default='INTAKE_DOCUMENT_VERSION', max_length=50, verbose_name='Aggregate type'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='available_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Available at'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Error message'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='event_type',
            field=models.CharField(choices=[('GENERATE_INTAKE_PDF', 'Generate intake PDF'), ('HIDRIVE_UPLOAD_INTAKE_PDF', 'HiDrive upload intake PDF')], max_length=40, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Locked at'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='max_retries',
            field=models.SmallIntegerField(default=10, verbose_name='Max retries'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='payload',
            field=models.JSONField(default=dict, verbose_name='Payload'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='payload_schema_version',
            field=models.SmallIntegerField(default=1, verbose_name='Payload schema version'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Processed at'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='retry_count',
            field=models.SmallIntegerField(default=0, verbose_name='Retry count'),
        ),
        migrations.AlterField(
            model_name='patientintakeconsent',
            name='accepted',
            field=models.BooleanField(verbose_name='Accepted'),
        ),
        migrations.AlterField(
            model_name='patientintakeconsent',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Accepted at'),
        ),
        migrations.AlterField(
            model_name='patientintakeconsent',
            name='selected_option_code',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Selected option code'),
        ),
        migrations.AlterField(
            model_name='patientintakeconsent',
            name='selected_option_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='Selected option codes'),
        ),
        migrations.AlterField(
            model_name='patientintakeform',
            name='anamnesis_payload',
            field=models.JSONField(default=dict, verbose_name='Anamnesis payload'),
        ),
        migrations.AlterField(
            model_name='patientintakeform',
            name='anamnesis_schema_version',
            field=models.SmallIntegerField(default=1, verbose_name='Anamnesis schema version'),
        ),
        migrations.AlterField(
            model_name='patientintakeform',
            name='body_map_data',
            field=models.JSONField(default=list, verbose_name='Body map data'),
        ),
        migrations.AlterField(
            model_name='patientintakeform',
            name='body_map_schema_version',
            field=models.SmallIntegerField(default=1, verbose_name='Body map schema version'),
        ),
        migrations.AlterField(
            model_name='patientintakeform',
            name='signature_file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Signature file path'),
        ),
        migrations.AlterField(
            model_name='patientintakeform',
            name='signature_sha256',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Signature sha256'),
        ),
        migrations.AlterField(
            model_name='patientintakeform',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submitted at'),
        ),
    ]
