# Generated by Django 6.0.4 on 2026-04-15 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0023_consent_teledermatologie'),
        ('reception', '0035_alter_patientformsession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anamnesisoptiondefinition',
            options={'verbose_name': 'Anamnesis option definition', 'verbose_name_plural': 'Anamnesis option definitions'},
        ),
        migrations.AlterModelOptions(
            name='anamnesisquestiondefinition',
            options={'verbose_name': 'Anamnesis question definition', 'verbose_name_plural': 'Anamnesis question definitions'},
        ),
        migrations.AlterModelOptions(
            name='consentdefinition',
            options={'verbose_name': 'Consent definition', 'verbose_name_plural': 'Consent definitions'},
        ),
        migrations.AlterModelOptions(
            name='intakedocumentversion',
            options={'verbose_name': 'Intake document version', 'verbose_name_plural': 'Intake document versions'},
        ),
        migrations.AlterModelOptions(
            name='intakeoutboxevent',
            options={'verbose_name': 'Intake outbox event', 'verbose_name_plural': 'Intake outbox events'},
        ),
        migrations.AlterModelOptions(
            name='patientintakeconsent',
            options={'verbose_name': 'Patient intake consent', 'verbose_name_plural': 'Patient intake consents'},
        ),
        migrations.AlterModelOptions(
            name='patientintakeform',
            options={'verbose_name': 'Patient intake form', 'verbose_name_plural': 'Patient intake forms'},
        ),
        migrations.AlterField(
            model_name='anamnesisoptiondefinition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='anamnesisoptiondefinition',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='intake.anamnesisquestiondefinition', verbose_name='Anamnesis question'),
        ),
        migrations.AlterField(
            model_name='anamnesisquestiondefinition',
            name='answer_type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'Single choice'), ('MULTI_CHOICE', 'Multi choice'), ('BOOLEAN', 'Boolean'), ('TEXT_OPTIONAL', 'Text optional')], default='SINGLE_CHOICE', max_length=30, verbose_name='Answer type'),
        ),
        migrations.AlterField(
            model_name='anamnesisquestiondefinition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='consentdefinition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='intakedocumentversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='intakedocumentversion',
            name='intake_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_versions', to='intake.patientintakeform', verbose_name='Intake form'),
        ),
        migrations.AlterField(
            model_name='intakedocumentversion',
            name='pdf_generation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='PDF generation status'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='aggregate_id',
            field=models.UUIDField(verbose_name='Aggregate ID'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='intake_document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='intake.intakedocumentversion', verbose_name='Intake document version'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('FAILED', 'Failed'), ('DEAD_LETTER', 'Dead letter')], default='PENDING', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='intakeoutboxevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='patientintakeconsent',
            name='consent_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='intake_consents', to='intake.consentdefinition', verbose_name='Consent definition'),
        ),
        migrations.AlterField(
            model_name='patientintakeconsent',
            name='intake_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='intake.patientintakeform', verbose_name='Intake form'),
        ),
        migrations.AlterField(
            model_name='patientintakeform',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='patientintakeform',
            name='form_status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In progress'), ('SUBMITTED', 'Submitted')], default='IN_PROGRESS', max_length=20, verbose_name='Form status'),
        ),
        migrations.AlterField(
            model_name='patientintakeform',
            name='queue_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intake_form', to='reception.queueentry', verbose_name='Queue entry'),
        ),
        migrations.AlterField(
            model_name='patientintakeform',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='intake_form', to='reception.patientformsession', verbose_name='Patient form session'),
        ),
        migrations.AlterField(
            model_name='patientintakeform',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
