# Generated by Django 6.0.6 on 2026-08-31 15:02

import uuid

import django.db.models.deletion
from django.db import migrations, models


def backfill_standard_process_types(apps, schema_editor):
    ConsentDefinition = apps.get_model("intake", "ConsentDefinition")
    ConsentDefinitionProcess = apps.get_model("intake", "ConsentDefinitionProcess")
    AnamnesisQuestionDefinition = apps.get_model(
        "intake", "AnamnesisQuestionDefinition"
    )
    AnamnesisQuestionDefinitionProcess = apps.get_model(
        "intake", "AnamnesisQuestionDefinitionProcess"
    )
    standard = "STANDARD"
    for definition in ConsentDefinition.objects.all().iterator():
        ConsentDefinitionProcess.objects.get_or_create(
            consent_definition=definition,
            process_type=standard,
        )
    for definition in AnamnesisQuestionDefinition.objects.all().iterator():
        AnamnesisQuestionDefinitionProcess.objects.get_or_create(
            question_definition=definition,
            process_type=standard,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0028_patientintakeform_json_blank"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnamnesisQuestionDefinitionProcess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("TELEDERM", "Teledermatology"),
                        ],
                        max_length=20,
                        verbose_name="Process type",
                    ),
                ),
                (
                    "question_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_links",
                        to="intake.anamnesisquestiondefinition",
                        verbose_name="Anamnesis question definition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anamnesis question process",
                "verbose_name_plural": "Anamnesis question processes",
                "db_table": "anamnesis_question_definition_process",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("question_definition", "process_type"),
                        name="anamnesis_question_process_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ConsentDefinitionProcess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "process_type",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("TELEDERM", "Teledermatology"),
                        ],
                        max_length=20,
                        verbose_name="Process type",
                    ),
                ),
                (
                    "consent_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="process_links",
                        to="intake.consentdefinition",
                        verbose_name="Consent definition",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consent definition process",
                "verbose_name_plural": "Consent definition processes",
                "db_table": "consent_definition_process",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("consent_definition", "process_type"),
                        name="consent_definition_process_unique",
                    )
                ],
            },
        ),
        migrations.RunPython(
            backfill_standard_process_types, migrations.RunPython.noop
        ),
    ]
