repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: python -m black
        language: system
        types: [python]
        exclude: /migrations/

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.15.1"
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        exclude: /migrations/
        types: [python]
