# Generated by Django 4.2.4 on 2026-02-16 22:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'clinic_site',
            },
        ),
        migrations.CreateModel(
            name='ConsultingRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'consulting_room',
            },
        ),
        migrations.CreateModel(
            name='DailyQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('queue_date', models.DateField()),
                ('shift_code', models.CharField(choices=[('FULL_DAY', 'Full day'), ('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], default='FULL_DAY', max_length=20)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORT', 'Import')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'daily_queue',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('doctolib_patient_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('identity_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('TEMPORARY', 'Temporary')], default='TEMPORARY', max_length=20)),
                ('identity_alert_created_at', models.DateTimeField(blank=True, null=True)),
                ('identity_resolution_due_at', models.DateTimeField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=150, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(default='DE', max_length=2)),
                ('external_source', models.CharField(blank=True, choices=[('DOCTOLIB_EXPORT', 'Doctolib Export'), ('OTHER', 'Other')], max_length=30, null=True)),
                ('external_source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='PatientContactHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'patient_contact_history',
            },
        ),
        migrations.CreateModel(
            name='PatientFormSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('form_locale', models.CharField(default='de-DE', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patient_form_session',
            },
        ),
        migrations.CreateModel(
            name='PatientImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file_name', models.CharField(max_length=255)),
                ('source_file_sha256', models.CharField(max_length=64)),
                ('import_type', models.CharField(choices=[('DAILY_FILE_IMPORT', 'Daily file import'), ('EMERGENCY_TEMPLATE_IMPORT', 'Emergency template import')], default='DAILY_FILE_IMPORT', max_length=40)),
                ('source_system', models.CharField(choices=[('DOCTOLIB_EXPORT', 'Doctolib export'), ('OTHER', 'Other')], default='DOCTOLIB_EXPORT', max_length=40)),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with errors'), ('FAILED', 'Failed')], default='PROCESSING', max_length=30)),
                ('total_rows', models.IntegerField(default=0)),
                ('inserted_rows', models.IntegerField(default=0)),
                ('error_rows', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient_import_batch',
            },
        ),
        migrations.CreateModel(
            name='PatientImportError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField()),
                ('error_code', models.CharField(max_length=50)),
                ('error_message', models.TextField()),
                ('raw_row', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'patient_import_error',
            },
        ),
        migrations.CreateModel(
            name='TabletDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('device_code', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tablet_device',
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_status', models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In progress'), ('PATIENT_COMPLETED', 'Patient completed'), ('DOCTOR_IN_PROGRESS', 'Doctor in progress'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=30)),
                ('position_no', models.IntegerField()),
                ('visit_external_id', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='reception.patientformsession')),
            ],
            options={
                'db_table': 'queue_entry',
            },
        ),
    ]
