# Generated by Django 4.2.4 on 2026-02-16 22:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_queue_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='daily_queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reception.dailyqueue'),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='queue_entries', to='reception.patient'),
        ),
        migrations.AddField(
            model_name='patientimporterror',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='reception.patientimportbatch'),
        ),
        migrations.AddField(
            model_name='patientimportbatch',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='import_batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientformsession',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_form_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientformsession',
            name='queue_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_sessions', to='reception.queueentry'),
        ),
        migrations.AddField(
            model_name='patientformsession',
            name='tablet_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='reception.tabletdevice'),
        ),
        migrations.AddField(
            model_name='patientcontacthistory',
            name='changed_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientcontacthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_history', to='reception.patient'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name', 'date_of_birth'], name='patient_last_na_713538_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['phone'], name='patient_phone_8e2162_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['identity_status', '-created_at'], name='patient_identit_749f01_idx'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.UniqueConstraint(fields=('external_source', 'external_source_id'), name='patient_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('phone__regex', '^[0-9+() -]{7,20}$')), name='patient_phone_format'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('identity_status__in', ['CONFIRMED', 'TEMPORARY'])), name='patient_identity_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('doctolib_patient_id__isnull', False), models.Q(('identity_alert_created_at__isnull', False), ('identity_resolution_due_at__isnull', False)), _connector='OR'), name='patient_temp_identity_requires_alert'),
        ),
        migrations.AddConstraint(
            model_name='patient',
            constraint=models.CheckConstraint(condition=models.Q(('identity_resolution_due_at__isnull', True), ('identity_alert_created_at__isnull', True), ('identity_resolution_due_at__gte', models.F('identity_alert_created_at')), _connector='OR'), name='patient_identity_due_after_alert'),
        ),
        migrations.AddField(
            model_name='dailyqueue',
            name='clinic_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='daily_queues', to='reception.clinicsite'),
        ),
        migrations.AddField(
            model_name='dailyqueue',
            name='consulting_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='daily_queues', to='reception.consultingroom'),
        ),
        migrations.AddField(
            model_name='dailyqueue',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_queues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='consultingroom',
            name='clinic_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='reception.clinicsite'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['daily_queue', 'entry_status', 'position_no'], name='queue_entry_daily_q_1ec636_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['patient', '-created_at'], name='queue_entry_patient_2d38c1_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['active_session'], name='queue_entry_active__265442_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(condition=models.Q(('entry_status__in', ['WAITING', 'IN_PROGRESS'])), fields=['daily_queue', 'position_no'], name='qentry_active_pos_idx'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(fields=('daily_queue', 'position_no'), name='queue_entry_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='queueentry',
            constraint=models.UniqueConstraint(condition=models.Q(('visit_external_id__isnull', False)), fields=('daily_queue', 'visit_external_id'), name='queue_entry_visit_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='patientimporterror',
            constraint=models.CheckConstraint(condition=models.Q(('row_number__gt', 0)), name='import_error_row_positive'),
        ),
        migrations.AddIndex(
            model_name='patientimportbatch',
            index=models.Index(fields=['status', '-created_at'], name='patient_imp_status_bf7d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='patientimportbatch',
            index=models.Index(fields=['source_system', '-created_at'], name='patient_imp_source__24ac3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientimportbatch',
            constraint=models.CheckConstraint(condition=models.Q(('total_rows__gte', 0), ('inserted_rows__gte', 0), ('error_rows__gte', 0)), name='import_batch_non_negative_counts'),
        ),
        migrations.AddIndex(
            model_name='patientformsession',
            index=models.Index(fields=['queue_entry', 'consumed_at'], name='patient_for_queue_e_9f3ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='patientformsession',
            index=models.Index(fields=['queue_entry', '-created_at'], name='patient_for_queue_e_f94258_idx'),
        ),
        migrations.AddIndex(
            model_name='patientformsession',
            index=models.Index(fields=['form_locale', '-created_at'], name='patient_for_form_lo_dec5f1_idx'),
        ),
        migrations.AddIndex(
            model_name='patientformsession',
            index=models.Index(condition=models.Q(('consumed_at__isnull', True)), fields=['expires_at'], name='session_unconsumed_expires_idx'),
        ),
        migrations.AddConstraint(
            model_name='patientformsession',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='session_expiry_after_create'),
        ),
        migrations.AddConstraint(
            model_name='patientformsession',
            constraint=models.CheckConstraint(condition=models.Q(('form_locale__regex', '^(de|en)(-[A-Z]{2})?$')), name='session_locale_format'),
        ),
        migrations.AddConstraint(
            model_name='patientformsession',
            constraint=models.CheckConstraint(condition=models.Q(('consumed_at__isnull', True), ('consumed_at__lte', models.F('expires_at')), _connector='OR'), name='session_consumed_before_expiry'),
        ),
        migrations.AddIndex(
            model_name='dailyqueue',
            index=models.Index(fields=['queue_date'], name='daily_queue_queue_d_c8b4c3_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailyqueue',
            constraint=models.UniqueConstraint(fields=('queue_date', 'clinic_site', 'consulting_room', 'shift_code'), name='daily_queue_unique_slot'),
        ),
        migrations.AddConstraint(
            model_name='consultingroom',
            constraint=models.UniqueConstraint(fields=('clinic_site', 'code'), name='consulting_room_site_code_unique'),
        ),
    ]
