# Generated by Django (process poczekalni: wycofanie tokenu)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientformsession",
            name="token_hash",
        ),
    ]
