# Generated by Django (process poczekalni: TabletDevice tylko android_id)

from django.db import migrations, models


def populate_android_id_from_device_code(apps, schema_editor):
    TabletDevice = apps.get_model("reception", "TabletDevice")
    for device in TabletDevice.objects.all():
        device.android_id = device.device_code or str(device.id)
        device.save(update_fields=["android_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0003_remove_patientformsession_token_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="tabletdevice",
            name="android_id",
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.RunPython(populate_android_id_from_device_code, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="tabletdevice",
            name="name",
        ),
        migrations.RemoveField(
            model_name="tabletdevice",
            name="device_code",
        ),
        migrations.AlterField(
            model_name="tabletdevice",
            name="android_id",
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
