# Generated by Django 6.0.2 on 2026-03-03 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0012_seed_today_queue_20_patients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyqueue',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_queues', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinic_sites',
            field=models.ManyToManyField(blank=True, db_table='patient_clinic_site', related_name='patients', to='reception.clinicsite'),
        ),
    ]
