# Generated by Django 6.0.2 on 2026-03-03 20:46

import logging

from django.db import migrations

logger = logging.getLogger(__name__)

def backfill_data(apps, schema_editor):
    StaffUser = apps.get_model('users', 'StaffUser')
    Patient = apps.get_model('reception', 'Patient')
    DailyQueue = apps.get_model('reception', 'DailyQueue')
    QueueEntry = apps.get_model('reception', 'QueueEntry')
    MedicalDocument = apps.get_model('medical', 'MedicalDocument')
    AuditEvent = apps.get_model('operations', 'AuditEvent')

    # 1. Fill staff_user_clinic_site
    for user in StaffUser.objects.filter(consulting_room__isnull=False):
        user.clinic_sites.add(user.consulting_room.clinic_site_id)

    for queue in DailyQueue.objects.filter(created_by_user__isnull=False).select_related('created_by_user'):
        if queue.created_by_user.role == 'DOCTOR':
            queue.created_by_user.clinic_sites.add(queue.clinic_site_id)

    # 2. Fill daily_queue.assigned_doctor_id
    for queue in DailyQueue.objects.all():
        doctors = list(StaffUser.objects.filter(
            created_medical_documents__queue_entry__daily_queue=queue
        ).distinct())
        if doctors:
            queue.assigned_doctor = doctors[0]
        else:
            if queue.created_by_user.role == 'DOCTOR':
                queue.assigned_doctor = queue.created_by_user
        
        if queue.assigned_doctor:
            queue.save(update_fields=['assigned_doctor'])

    # 3. Fill patient_clinic_site
    for entry in QueueEntry.objects.select_related('patient', 'daily_queue__clinic_site'):
        entry.patient.clinic_sites.add(entry.daily_queue.clinic_site_id)

    # 4. Fill audit_event context
    for event in AuditEvent.objects.all():
        updated = False
        if event.medical_document_id:
            doc = MedicalDocument.objects.select_related('queue_entry__daily_queue').filter(id=event.medical_document_id).first()
            if doc:
                event.context_clinic_site_id = doc.queue_entry.daily_queue.clinic_site_id
                
                metadata = event.metadata or {}
                if 'clinic_site_id' not in metadata:
                    metadata['clinic_site_id'] = str(doc.queue_entry.daily_queue.clinic_site_id)
                    updated = True
                
                assigned_doctor_id = doc.queue_entry.daily_queue.assigned_doctor_id
                if assigned_doctor_id and 'assigned_doctor_id' not in metadata:
                    metadata['assigned_doctor_id'] = str(assigned_doctor_id)
                    updated = True
                    
                if 'medical_document_id' not in metadata:
                    metadata['medical_document_id'] = str(doc.id)
                    updated = True
                
                if updated:
                    event.metadata = metadata
                    event.save(update_fields=['context_clinic_site', 'metadata'])

def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0013_dailyqueue_assigned_doctor_patient_clinic_sites'),
        ('users', '0005_staffuser_clinic_sites'),
        ('medical', '0006_remove_doctortexttemplate_doctor_template_global_owner_consistency_and_more'),
        ('operations', '0003_auditevent_context_clinic_site'),
    ]

    operations = [
        migrations.RunPython(backfill_data, reverse_backfill),
    ]
