# Generated by Django 6.0.2 on 2026-03-03 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0014_backfill_doctor_scopes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dailyqueue',
            index=models.Index(fields=['assigned_doctor', 'queue_date', 'status'], name='daily_queue_assigne_397070_idx'),
        ),
    ]
