# Generated by Django 6.0.2 on 2026-03-04 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0015_dailyqueue_daily_queue_assigne_397070_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clinicsite',
            options={'verbose_name': 'Clinic site', 'verbose_name_plural': 'Clinic sites'},
        ),
        migrations.AlterModelOptions(
            name='consultingroom',
            options={'verbose_name': 'Consulting room', 'verbose_name_plural': 'Consulting rooms'},
        ),
        migrations.AlterModelOptions(
            name='dailyqueue',
            options={'verbose_name': 'Daily queue', 'verbose_name_plural': 'Daily queues'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Patient', 'verbose_name_plural': 'Patients'},
        ),
        migrations.AlterModelOptions(
            name='queueentry',
            options={'verbose_name': 'Queue entry', 'verbose_name_plural': 'Queue entries'},
        ),
        migrations.AlterField(
            model_name='clinicsite',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='clinicsite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='clinicsite',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='clinicsite',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='consultingroom',
            name='clinic_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rooms', to='reception.clinicsite', verbose_name='Clinic site'),
        ),
        migrations.AlterField(
            model_name='consultingroom',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='consultingroom',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='consultingroom',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='consultingroom',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='dailyqueue',
            name='clinic_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='daily_queues', to='reception.clinicsite', verbose_name='Clinic site'),
        ),
        migrations.AlterField(
            model_name='dailyqueue',
            name='queue_date',
            field=models.DateField(verbose_name='Queue date'),
        ),
        migrations.AlterField(
            model_name='dailyqueue',
            name='shift_code',
            field=models.CharField(choices=[('FULL_DAY', 'Full day'), ('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon'), ('EVENING', 'Evening')], default='FULL_DAY', max_length=20, verbose_name='Shift code'),
        ),
        migrations.AlterField(
            model_name='dailyqueue',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('IMPORT', 'Import')], default='MANUAL', max_length=20, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='dailyqueue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='country_code',
            field=models.CharField(default='DE', max_length=2, verbose_name='Country code'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_of_birth',
            field=models.DateField(verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctolib_patient_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Doctolib patient id'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='external_source_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='External source id'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identity_alert_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Identity alert created at'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='identity_resolution_due_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Identity resolution due at'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='patientcontacthistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Changed at'),
        ),
        migrations.AlterField(
            model_name='patientcontacthistory',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='patientcontacthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_history', to='reception.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='patientcontacthistory',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='patientcontacthistory',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='patientformsession',
            name='consumed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Consumed at'),
        ),
        migrations.AlterField(
            model_name='patientformsession',
            name='expires_at',
            field=models.DateTimeField(verbose_name='Expires at'),
        ),
        migrations.AlterField(
            model_name='patientformsession',
            name='form_locale',
            field=models.CharField(default='de-DE', max_length=10, verbose_name='Form locale'),
        ),
        migrations.AlterField(
            model_name='patientimportbatch',
            name='error_rows',
            field=models.IntegerField(default=0, verbose_name='Error rows'),
        ),
        migrations.AlterField(
            model_name='patientimportbatch',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Finished at'),
        ),
        migrations.AlterField(
            model_name='patientimportbatch',
            name='inserted_rows',
            field=models.IntegerField(default=0, verbose_name='Inserted rows'),
        ),
        migrations.AlterField(
            model_name='patientimportbatch',
            name='source_file_name',
            field=models.CharField(max_length=255, verbose_name='Source file name'),
        ),
        migrations.AlterField(
            model_name='patientimportbatch',
            name='source_file_sha256',
            field=models.CharField(max_length=64, verbose_name='Source file sha256'),
        ),
        migrations.AlterField(
            model_name='patientimportbatch',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('COMPLETED_WITH_ERRORS', 'Completed with errors'), ('FAILED', 'Failed')], default='PROCESSING', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='patientimportbatch',
            name='total_rows',
            field=models.IntegerField(default=0, verbose_name='Total rows'),
        ),
        migrations.AlterField(
            model_name='patientimporterror',
            name='error_code',
            field=models.CharField(max_length=50, verbose_name='Error code'),
        ),
        migrations.AlterField(
            model_name='patientimporterror',
            name='error_message',
            field=models.TextField(verbose_name='Error message'),
        ),
        migrations.AlterField(
            model_name='patientimporterror',
            name='raw_row',
            field=models.JSONField(blank=True, null=True, verbose_name='Raw row'),
        ),
        migrations.AlterField(
            model_name='patientimporterror',
            name='row_number',
            field=models.IntegerField(verbose_name='Row number'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='appointment_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Appointment time'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='daily_queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reception.dailyqueue', verbose_name='Daily queue'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='queue_entries', to='reception.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='position_no',
            field=models.IntegerField(verbose_name='Position no'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='visit_external_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Visit external id'),
        ),
        migrations.AlterField(
            model_name='tabletdevice',
            name='android_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='Android id'),
        ),
        migrations.AlterField(
            model_name='tabletdevice',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='tabletdevice',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last seen at'),
        ),
    ]
