# Generated by Django 6.0.2 on 2026-03-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0026_seed_queue_20_patients_2026_03_18"),
    ]

    operations = [
    ]
