# Generated by Django 6.0.2 on 2026-03-23

from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0030_purge_seed_clinics_demo_muc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyqueue",
            name="assigned_doctor",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to=Q(("groups__name", "Doctor")),
                null=True,
                on_delete=models.SET_NULL,
                related_name="assigned_queues",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
