# Generated by Django 6.0.4 on 2026-04-15 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0034_patient_incoming_pdf_name_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientformsession',
            options={'verbose_name': 'Patient form session', 'verbose_name_plural': 'Patient form sessions'},
        ),
        migrations.AlterModelOptions(
            name='patientimportbatch',
            options={'verbose_name': 'Patient import batch', 'verbose_name_plural': 'Patient import batches'},
        ),
        migrations.AlterModelOptions(
            name='patientimporterror',
            options={'verbose_name': 'Patient import error', 'verbose_name_plural': 'Patient import errors'},
        ),
        migrations.AlterModelOptions(
            name='tabletdevice',
            options={'verbose_name': 'Tablet device', 'verbose_name_plural': 'Tablet devices'},
        ),
        migrations.AlterField(
            model_name='dailyqueue',
            name='assigned_doctor',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('groups__name', 'Doctor')), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_queues', to=settings.AUTH_USER_MODEL, verbose_name='Assigned doctor'),
        ),
        migrations.AlterField(
            model_name='dailyqueue',
            name='consulting_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='daily_queues', to='reception.consultingroom', verbose_name='Consulting room'),
        ),
        migrations.AlterField(
            model_name='dailyqueue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='dailyqueue',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_queues', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='dailyqueue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='clinic_sites',
            field=models.ManyToManyField(blank=True, db_table='patient_clinic_site', related_name='patients', to='reception.clinicsite', verbose_name='Clinic sites'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='patientformsession',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='patientformsession',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_form_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='patientformsession',
            name='queue_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_sessions', to='reception.queueentry', verbose_name='Queue entry'),
        ),
        migrations.AlterField(
            model_name='patientformsession',
            name='tablet_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='reception.tabletdevice', verbose_name='Tablet device'),
        ),
        migrations.AlterField(
            model_name='patientimportbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='patientimportbatch',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='import_batches', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='patientimportbatch',
            name='import_type',
            field=models.CharField(choices=[('DAILY_FILE_IMPORT', 'Daily file import'), ('EMERGENCY_TEMPLATE_IMPORT', 'Emergency template import')], default='DAILY_FILE_IMPORT', max_length=40, verbose_name='Import type'),
        ),
        migrations.AlterField(
            model_name='patientimportbatch',
            name='source_system',
            field=models.CharField(choices=[('DOCTOLIB_EXPORT', 'Doctolib export'), ('OTHER', 'Other')], default='DOCTOLIB_EXPORT', max_length=40, verbose_name='Source system'),
        ),
        migrations.AlterField(
            model_name='patientimporterror',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='reception.patientimportbatch', verbose_name='Import batch'),
        ),
        migrations.AlterField(
            model_name='patientimporterror',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='active_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='reception.patientformsession', verbose_name='Active session'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_queue_entries', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='entry_status',
            field=models.CharField(choices=[('WAITING', 'Waiting'), ('IN_PROGRESS', 'In progress'), ('PATIENT_COMPLETED', 'Patient completed'), ('DOCTOR_IN_PROGRESS', 'Doctor in progress'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], default='WAITING', max_length=30, verbose_name='Entry status'),
        ),
        migrations.AlterField(
            model_name='queueentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='tabletdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
    ]
