# Generated by Django 6.0.6 on 2026-08-30 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0043_normalize_patient_email_storage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='queueentry',
            name='ausfallhonorar',
            field=models.BooleanField(default=False, help_text='Manual fee for no-show, refused exam, or short-notice cancellation. Appears on the accounting Ausfallhonorar list.', verbose_name='Ausfallhonorar'),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='ausfallhonorar_set_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ausfallhonorar set at'),
        ),
        migrations.AddField(
            model_name='queueentry',
            name='ausfallhonorar_set_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausfallhonorar_set_queue_entries', to=settings.AUTH_USER_MODEL, verbose_name='Ausfallhonorar set by'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(condition=models.Q(('ausfallhonorar', True)), fields=['ausfallhonorar'], name='qentry_ausfall_true_idx'),
        ),
    ]
