# Generated by Django 6.0.6 on 2026-08-31 15:02

from django.conf import settings
from django.db import migrations, models


def cancel_duplicate_queue_entries(apps, schema_editor):
    """Keep one active row per (queue, patient, process_type); cancel extras.

    KEEP prefers submitted intake / completed / paper / document over empty
    WAITING (reimport). Two clinical rows in one group abort the migration.
    Paper authorizations on cancelled extras are deleted (same as revoke).
    Reverse is noop: CANCELLED is not restored.
    """
    from apps.reception.queue_duplicate_resolution import cancel_extra_queue_entries

    db_alias = schema_editor.connection.alias
    cancel_extra_queue_entries(
        QueueEntry=apps.get_model("reception", "QueueEntry"),
        PatientIntakeForm=apps.get_model("intake", "PatientIntakeForm"),
        PaperIntakeAuthorization=apps.get_model("medical", "PaperIntakeAuthorization"),
        MedicalDocument=apps.get_model("medical", "MedicalDocument"),
        PatientFormSession=apps.get_model("reception", "PatientFormSession"),
        db_alias=db_alias,
    )


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0044_queueentry_ausfallhonorar"),
        ("intake", "0028_patientintakeform_json_blank"),
        ("medical", "0023_medicaldocument_edit_session_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="process_type",
            field=models.CharField(
                choices=[("STANDARD", "Standard"), ("TELEDERM", "Teledermatology")],
                default="STANDARD",
                max_length=20,
                verbose_name="Process type",
            ),
        ),
        migrations.RunPython(
            cancel_duplicate_queue_entries,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="queueentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("entry_status", "CANCELLED"), _negated=True),
                fields=("daily_queue", "patient", "process_type"),
                name="queue_entry_process_type_unique",
            ),
        ),
    ]
