# Generated by Django 6.0.6 on 2026-08-31 15:02

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.utils import timezone

_STATUS_RANK = {
    "DOCTOR_IN_PROGRESS": 5,
    "PATIENT_COMPLETED": 4,
    "PAPER_INTAKE_COMPLETED": 3,
    "IN_PROGRESS": 2,
    "WAITING": 1,
}


def cancel_duplicate_queue_entries(apps, schema_editor):
    """Keep one active row per (queue, patient, process_type); cancel extras.

    Historical local/prod data can have several non-cancelled STANDARD entries
    for the same patient in one DailyQueue. The unique constraint cannot be
    created until those extras are out of the partial index.
    """
    QueueEntry = apps.get_model("reception", "QueueEntry")
    db_alias = schema_editor.connection.alias
    now = timezone.now()
    groups = (
        QueueEntry.objects.using(db_alias)
        .exclude(entry_status="CANCELLED")
        .values("daily_queue_id", "patient_id", "process_type")
        .annotate(n=Count("id"))
        .filter(n__gt=1)
    )
    to_cancel: list = []
    for group in groups:
        rows = list(
            QueueEntry.objects.using(db_alias)
            .filter(
                daily_queue_id=group["daily_queue_id"],
                patient_id=group["patient_id"],
                process_type=group["process_type"],
            )
            .exclude(entry_status="CANCELLED")
            .only("id", "entry_status", "created_at")
        )
        rows.sort(
            key=lambda row: (
                -_STATUS_RANK.get(row.entry_status, 0),
                row.created_at,
                str(row.pk),
            )
        )
        for extra in rows[1:]:
            extra.entry_status = "CANCELLED"
            extra.updated_at = now
            to_cancel.append(extra)
    if to_cancel:
        QueueEntry.objects.using(db_alias).bulk_update(
            to_cancel, ["entry_status", "updated_at"]
        )


class Migration(migrations.Migration):

    dependencies = [
        ("reception", "0044_queueentry_ausfallhonorar"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="queueentry",
            name="process_type",
            field=models.CharField(
                choices=[("STANDARD", "Standard"), ("TELEDERM", "Teledermatology")],
                default="STANDARD",
                max_length=20,
                verbose_name="Process type",
            ),
        ),
        migrations.RunPython(
            cancel_duplicate_queue_entries,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="queueentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("entry_status", "CANCELLED"), _negated=True),
                fields=("daily_queue", "patient", "process_type"),
                name="queue_entry_process_type_unique",
            ),
        ),
    ]
