from __future__ import annotations

from django.urls import path

from apps.intake.api_views import (
    intake_form_anamnesis_view,
    intake_form_consents_view,
    intake_form_detail_view,
    intake_form_signature_view,
    intake_form_submit_view,
    intake_outbox_event_retry_view,
    intake_outbox_events_view,
    intake_outbox_process_view,
)
from apps.intake.document_views import (
    intake_document_detail_view,
    intake_document_preview_pdf_view,
    intake_documents_view,
)
from apps.medical.api_views import (
    doctor_text_template_detail_view,
    doctor_text_templates_view,
    medical_document_detail_view,
    medical_document_draft_view,
    medical_document_preview_pdf_view,
    medical_document_publish_view,
    medical_document_retry_processing_view,
    medical_document_revoke_view,
    medical_document_version_detail_view,
    medical_document_versions_view,
    medical_document_audit_trail_view,
    medical_documents_view,
)
from apps.outbox.api_views import (
    operations_outbox_process_view,
    operations_retention_run_view,
    outbox_event_retry_view,
    outbox_events_view,
)
from apps.operations.api_views import (
    audit_events_view,
    observability_health_view,
    observability_metrics_view,
)
from apps.reception.api_views import (
    clinic_site_detail_view,
    clinic_sites_view,
    consulting_room_detail_view,
    consulting_rooms_view,
    daily_queue_detail_view,
    daily_queue_entries_view,
    daily_queues_view,
    import_batch_detail_view,
    import_batch_errors_view,
    import_batches_view,
    patient_contact_history_view,
    patient_detail_view,
    patients_view,
    queue_entry_detail_view,
    queue_entry_sessions_view,
    tablet_device_detail_view,
    tablet_device_heartbeat_view,
    tablet_devices_view,
)
from apps.patient_results.api_views import (
    patient_results_documents_view,
    patient_results_download_view,
    patient_results_request_otp_view,
    patient_results_verify_otp_view,
)
from apps.users.api_views import (
    auth_login_view,
    auth_logout_view,
    auth_me_view,
    staff_user_clinic_sites_view,
    staff_user_detail_view,
    staff_users_view,
)


urlpatterns = [
    path(
        "observability/health",
        observability_health_view,
        name="observability-health",
    ),
    path(
        "observability/metrics",
        observability_metrics_view,
        name="observability-metrics",
    ),
    path(
        "auth/login",
        auth_login_view,
        name="auth-login",
    ),
    path(
        "auth/logout",
        auth_logout_view,
        name="auth-logout",
    ),
    path(
        "auth/me",
        auth_me_view,
        name="auth-me",
    ),
    path(
        "staff-users",
        staff_users_view,
        name="staff-users",
    ),
    path(
        "staff-users/<uuid:staff_user_id>",
        staff_user_detail_view,
        name="staff-user-detail",
    ),
    path(
        "staff-users/<uuid:staff_user_id>/clinic-sites",
        staff_user_clinic_sites_view,
        name="staff-user-clinic-sites",
    ),
    path(
        "doctor-text-templates",
        doctor_text_templates_view,
        name="doctor-text-templates",
    ),
    path(
        "doctor-text-templates/<uuid:template_id>",
        doctor_text_template_detail_view,
        name="doctor-text-template-detail",
    ),
    path(
        "audit-events",
        audit_events_view,
        name="audit-events",
    ),
    path(
        "outbox-events",
        outbox_events_view,
        name="outbox-events",
    ),
    path(
        "outbox-events/<uuid:outbox_event_id>/retry",
        outbox_event_retry_view,
        name="outbox-event-retry",
    ),
    path(
        "operations/outbox/process",
        operations_outbox_process_view,
        name="operations-outbox-process",
    ),
    path(
        "operations/retention/run",
        operations_retention_run_view,
        name="operations-retention-run",
    ),
    path(
        "intake-outbox-events",
        intake_outbox_events_view,
        name="intake-outbox-events",
    ),
    path(
        "intake-outbox-events/<uuid:intake_outbox_event_id>/retry",
        intake_outbox_event_retry_view,
        name="intake-outbox-event-retry",
    ),
    path(
        "operations/intake-outbox/process",
        intake_outbox_process_view,
        name="operations-intake-outbox-process",
    ),
    path(
        "medical-documents",
        medical_documents_view,
        name="medical-documents",
    ),
    path(
        "medical-documents/<uuid:medical_document_id>",
        medical_document_detail_view,
        name="medical-document-detail",
    ),
    path(
        "medical-documents/<uuid:medical_document_id>/preview-pdf",
        medical_document_preview_pdf_view,
        name="medical-document-preview-pdf",
    ),
    path(
        "medical-documents/<uuid:medical_document_id>/versions",
        medical_document_versions_view,
        name="medical-document-versions",
    ),
    path(
        "medical-documents/<uuid:medical_document_id>/audit-trail",
        medical_document_audit_trail_view,
        name="medical-document-audit-trail",
    ),
    path(
        "medical-documents/<uuid:medical_document_id>/draft",
        medical_document_draft_view,
        name="medical-document-draft",
    ),
    path(
        "medical-documents/<uuid:medical_document_id>/publish",
        medical_document_publish_view,
        name="medical-document-publish",
    ),
    path(
        "medical-documents/<uuid:medical_document_id>/retry-processing",
        medical_document_retry_processing_view,
        name="medical-document-retry-processing",
    ),
    path(
        "medical-documents/<uuid:medical_document_id>/revoke",
        medical_document_revoke_view,
        name="medical-document-revoke",
    ),
    path(
        "medical-document-versions/<uuid:version_id>",
        medical_document_version_detail_view,
        name="medical-document-version-detail",
    ),
    path(
        "clinic-sites",
        clinic_sites_view,
        name="clinic-sites",
    ),
    path(
        "clinic-sites/<uuid:clinic_site_id>",
        clinic_site_detail_view,
        name="clinic-site-detail",
    ),
    path(
        "consulting-rooms",
        consulting_rooms_view,
        name="consulting-rooms",
    ),
    path(
        "consulting-rooms/<uuid:consulting_room_id>",
        consulting_room_detail_view,
        name="consulting-room-detail",
    ),
    path(
        "imports/batches",
        import_batches_view,
        name="import-batches",
    ),
    path(
        "imports/batches/<uuid:batch_id>",
        import_batch_detail_view,
        name="import-batch-detail",
    ),
    path(
        "imports/batches/<uuid:batch_id>/errors",
        import_batch_errors_view,
        name="import-batch-errors",
    ),
    path(
        "patients",
        patients_view,
        name="patients",
    ),
    path(
        "patients/<uuid:patient_id>",
        patient_detail_view,
        name="patient-detail",
    ),
    path(
        "patients/<uuid:patient_id>/contact-history",
        patient_contact_history_view,
        name="patient-contact-history",
    ),
    path(
        "daily-queues",
        daily_queues_view,
        name="daily-queues",
    ),
    path(
        "daily-queues/<uuid:daily_queue_id>",
        daily_queue_detail_view,
        name="daily-queue-detail",
    ),
    path(
        "daily-queues/<uuid:daily_queue_id>/entries",
        daily_queue_entries_view,
        name="daily-queue-entries",
    ),
    path(
        "queue-entries/<uuid:queue_entry_id>",
        queue_entry_detail_view,
        name="queue-entry-detail",
    ),
    path(
        "queue-entries/<uuid:queue_entry_id>/sessions",
        queue_entry_sessions_view,
        name="queue-entry-sessions",
    ),
    path(
        "tablet-devices",
        tablet_devices_view,
        name="tablet-devices",
    ),
    path(
        "tablet-devices/<uuid:tablet_device_id>",
        tablet_device_detail_view,
        name="tablet-device-detail",
    ),
    path(
        "tablet-devices/<uuid:tablet_device_id>/heartbeat",
        tablet_device_heartbeat_view,
        name="tablet-device-heartbeat",
    ),
    path(
        "intake-forms/<uuid:intake_form_id>/anamnesis",
        intake_form_anamnesis_view,
        name="intake-form-anamnesis",
    ),
    path(
        "intake-forms/<uuid:intake_form_id>/submit",
        intake_form_submit_view,
        name="intake-form-submit",
    ),
    path(
        "intake-forms/<uuid:intake_form_id>/consents",
        intake_form_consents_view,
        name="intake-form-consents",
    ),
    path(
        "intake-forms/<uuid:intake_form_id>/signature",
        intake_form_signature_view,
        name="intake-form-signature",
    ),
    path(
        "intake-forms/<uuid:intake_form_id>",
        intake_form_detail_view,
        name="intake-form-detail",
    ),
    path(
        "intake-documents",
        intake_documents_view,
        name="intake-documents",
    ),
    path(
        "intake-documents/<uuid:intake_document_version_id>",
        intake_document_detail_view,
        name="intake-document-detail",
    ),
    path(
        "intake-documents/<uuid:intake_document_version_id>/preview-pdf",
        intake_document_preview_pdf_view,
        name="intake-document-preview-pdf",
    ),
    path(
        "patient-results/request-otp",
        patient_results_request_otp_view,
        name="patient-results-request-otp",
    ),
    path(
        "patient-results/verify-otp",
        patient_results_verify_otp_view,
        name="patient-results-verify-otp",
    ),
    path(
        "patient-results/documents",
        patient_results_documents_view,
        name="patient-results-documents",
    ),
    path(
        "patient-results/documents/<uuid:version_id>/download",
        patient_results_download_view,
        name="patient-results-download",
    ),
]
