# Generated by Django 6.0.2 on 2026-02-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='translationkey',
            new_name='translation_categor_5887cc_idx',
            old_name='translation__categor_f7ee83_idx',
        ),
        migrations.RenameIndex(
            model_name='translationvalue',
            new_name='translation_languag_23afb3_idx',
            old_name='translation_language_7e9eca_idx',
        ),
    ]
