# Generated by Django 6.0.2 on 2026-03-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seed_doctor_template_select_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationcacheversion',
            name='language_code',
            field=models.CharField(max_length=5, verbose_name='Language code'),
        ),
        migrations.AlterField(
            model_name='translationcacheversion',
            name='version',
            field=models.BigIntegerField(default=1, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='translationkey',
            name='allowed_placeholders',
            field=models.JSONField(blank=True, default=list, verbose_name='Allowed placeholders'),
        ),
        migrations.AlterField(
            model_name='translationkey',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='translationkey',
            name='is_html_allowed',
            field=models.BooleanField(default=False, verbose_name='Is html allowed'),
        ),
        migrations.AlterField(
            model_name='translationkey',
            name='key',
            field=models.CharField(max_length=150, unique=True, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='translationvalue',
            name='language_code',
            field=models.CharField(max_length=5, verbose_name='Language code'),
        ),
        migrations.AlterField(
            model_name='translationvalue',
            name='value',
            field=models.TextField(verbose_name='Value'),
        ),
    ]
