# Generated by Django 6.0.2 on 2026-03-25 07:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_seed_other_api_and_admin_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='translationcacheversion',
            name='translation_cache_version_language_allowed',
        ),
        migrations.RemoveConstraint(
            model_name='translationvalue',
            name='translation_value_language_allowed',
        ),
        migrations.AlterField(
            model_name='translationcacheversion',
            name='language_code',
            field=models.CharField(choices=[('de-DE', 'German (Germany)'), ('en-GB', 'English (United Kingdom)'), ('pl-PL', 'Polish (Poland)')], max_length=5, verbose_name='Language code'),
        ),
        migrations.AlterField(
            model_name='translationvalue',
            name='language_code',
            field=models.CharField(choices=[('de-DE', 'German (Germany)'), ('en-GB', 'English (United Kingdom)'), ('pl-PL', 'Polish (Poland)')], max_length=5, verbose_name='Language code'),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE translation_value SET language_code = 'de-DE' WHERE language_code = 'de';"
                "UPDATE translation_value SET language_code = 'en-GB' WHERE language_code = 'en';"
                "UPDATE translation_value SET language_code = 'pl-PL' WHERE language_code = 'pl';"
                "UPDATE translation_cache_version SET language_code = 'de-DE' WHERE language_code = 'de';"
                "UPDATE translation_cache_version SET language_code = 'en-GB' WHERE language_code = 'en';"
                "UPDATE translation_cache_version SET language_code = 'pl-PL' WHERE language_code = 'pl';"
            ),
            reverse_sql=(
                "UPDATE translation_value SET language_code = 'de' WHERE language_code = 'de-DE';"
                "UPDATE translation_value SET language_code = 'en' WHERE language_code = 'en-GB';"
                "UPDATE translation_value SET language_code = 'pl' WHERE language_code = 'pl-PL';"
                "UPDATE translation_cache_version SET language_code = 'de' WHERE language_code = 'de-DE';"
                "UPDATE translation_cache_version SET language_code = 'en' WHERE language_code = 'en-GB';"
                "UPDATE translation_cache_version SET language_code = 'pl' WHERE language_code = 'pl-PL';"
            ),
        ),
        migrations.AddConstraint(
            model_name='translationcacheversion',
            constraint=models.CheckConstraint(condition=models.Q(('language_code__in', ['de-DE', 'en-GB', 'pl-PL'])), name='translation_cache_version_language_allowed'),
        ),
        migrations.AddConstraint(
            model_name='translationvalue',
            constraint=models.CheckConstraint(condition=models.Q(('language_code__in', ['de-DE', 'en-GB', 'pl-PL'])), name='translation_value_language_allowed'),
        ),
    ]
