# Generated by Django 6.0.4 on 2026-04-15 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_seed_doctor_pdf_lesion_numbers_heading_de'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='translationcacheversion',
            options={'verbose_name': 'Translation cache version', 'verbose_name_plural': 'Translation cache versions'},
        ),
        migrations.AlterModelOptions(
            name='translationkey',
            options={'verbose_name': 'Translation key', 'verbose_name_plural': 'Translation keys'},
        ),
        migrations.AlterModelOptions(
            name='translationvalue',
            options={'verbose_name': 'Translation value', 'verbose_name_plural': 'Translation values'},
        ),
        migrations.AlterField(
            model_name='translationcacheversion',
            name='category',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('reception', 'Reception'), ('waiting_room', 'Waiting room'), ('administration', 'Administration'), ('other', 'Other')], max_length=32, verbose_name='Translation category'),
        ),
        migrations.AlterField(
            model_name='translationcacheversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='translationcacheversion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='translationkey',
            name='category',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('reception', 'Reception'), ('waiting_room', 'Waiting room'), ('administration', 'Administration'), ('other', 'Other')], max_length=32, verbose_name='Translation category'),
        ),
        migrations.AlterField(
            model_name='translationkey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='translationkey',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated')], default='ACTIVE', max_length=16, verbose_name='Key status'),
        ),
        migrations.AlterField(
            model_name='translationkey',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='translationvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='translationvalue',
            name='translation_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='core.translationkey', verbose_name='Translation key'),
        ),
        migrations.AlterField(
            model_name='translationvalue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='translationvalue',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_translation_values', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
    ]
