# Generated by Django 4.2.4 on 2025-07-31 17:42

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('results', '0012_delete_pacjent_delete_rejestrator_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
            ],
            options={
                'verbose_name': 'Rejestrator',
                'verbose_name_plural': 'Rejestratorzy',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('results.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
