"""Seed data for telederm path CCE-004 (rash)."""

from __future__ import annotations

from typing import Any

from apps.telederm.models import TeledermAnswerType, TeledermSection
from apps.telederm.seed.helpers import (
    NONE,
    OTHER,
    PREGNANCY,
    YES,
    YES_NO,
    YES_NO_UNKNOWN,
    _ft,
    _opt,
    _q,
)

PATH_CODE = "CCE-004"

CCE004_QUESTIONS: list[dict[str, Any]] = [
    _q(
        "Q060",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=4000,
        text_de="Wo tritt der Hautausschlag auf?",
        text_en="Where does the rash occur?",
        text_pl="Gdzie występuje wysypka?",
        options=[
            _opt("FACE", label_de="Gesicht", label_en="Face", label_pl="Twarz"),
            _opt("NECK", label_de="Hals", label_en="Neck", label_pl="Szyja"),
            _opt("CHEST", label_de="Brustkorb", label_en="Chest", label_pl="Klatka"),
            _opt("ABDOMEN", label_de="Bauch", label_en="Abdomen", label_pl="Brzuch"),
            _opt("BACK", label_de="Rücken", label_en="Back", label_pl="Plecy"),
            _opt("ARMS", label_de="Arme", label_en="Arms", label_pl="Ręce"),
            _opt("HANDS", label_de="Hände", label_en="Hands", label_pl="Dłonie"),
            _opt("LEGS", label_de="Beine", label_en="Legs", label_pl="Nogi"),
            _opt("FEET", label_de="Füße", label_en="Feet", label_pl="Stopy"),
            _opt("AXILLAE", label_de="Achseln", label_en="Armpits", label_pl="Pachy"),
            _opt("GROINS", label_de="Leisten", label_en="Groins", label_pl="Pachwiny"),
            _opt(
                "GENITAL_AREA",
                label_de="Intimbereich",
                label_en="Genital area",
                label_pl="Okolica intymna",
            ),
            _opt(
                "WHOLE_BODY",
                label_de="Ganzer Körper",
                label_en="Whole body",
                label_pl="Całe ciało",
            ),
        ],
    ),
    _q(
        "Q061",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=4010,
        text_de="Seit wann besteht der Ausschlag?",
        text_en="How long has the rash been present?",
        text_pl="Od kiedy trwa?",
        options=[
            _opt("TODAY", label_de="Heute", label_en="Today", label_pl="Dzisiaj"),
            _opt(
                "TWO_TO_SEVEN_DAYS",
                label_de="2–7 Tage",
                label_en="2–7 days",
                label_pl="2–7 dni",
            ),
            _opt(
                "ONE_TO_FOUR_WEEKS",
                label_de="1–4 Wochen",
                label_en="1–4 weeks",
                label_pl="1–4 tygodnie",
            ),
            _opt(
                "ONE_TO_SIX_MONTHS",
                label_de="1–6 Monate",
                label_en="1–6 months",
                label_pl="1–6 miesięcy",
            ),
            _opt(
                "OVER_SIX_MONTHS",
                label_de="Länger als 6 Monate",
                label_en="More than 6 months",
                label_pl="Ponad 6 miesięcy",
            ),
        ],
    ),
    _q(
        "Q062",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=4020,
        text_de="Wie verhält sich der Ausschlag?",
        text_en="How is the rash behaving?",
        text_pl="Jak się zachowuje?",
        options=[
            _opt(
                "SPREADING",
                label_de="Breitet sich aus",
                label_en="Spreading",
                label_pl="Rozprzestrzenia się",
            ),
            _opt(
                "WORSENING",
                label_de="Verschlimmert sich",
                label_en="Worsening",
                label_pl="Nasila się",
            ),
            _opt(
                "IMPROVING",
                label_de="Bessert sich",
                label_en="Improving",
                label_pl="Ustępuje",
            ),
            _opt(
                "RECURRING",
                label_de="Tritt wiederholt auf",
                label_en="Recurring",
                label_pl="Nawraca",
            ),
            _opt(
                "NO_CHANGE",
                label_de="Ohne Veränderung",
                label_en="No change",
                label_pl="Bez zmian",
            ),
        ],
    ),
    _q(
        "Q063",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=4030,
        text_de="Welche Begleitsymptome treten auf?",
        text_en="What accompanying symptoms are present?",
        text_pl="Jakie objawy towarzyszą?",
        options=[
            _opt("ITCH", label_de="Juckreiz", label_en="Itch", label_pl="Świąd"),
            _opt("PAIN", label_de="Schmerzen", label_en="Pain", label_pl="Ból"),
            _opt(
                "BURNING",
                label_de="Brennen",
                label_en="Burning",
                label_pl="Pieczenie",
            ),
            _opt(
                "SWELLING",
                label_de="Schwellung",
                label_en="Swelling",
                label_pl="Obrzęk",
            ),
            _opt(
                "SCALING",
                label_de="Schuppung",
                label_en="Scaling",
                label_pl="Łuszczenie",
            ),
            _opt(
                "BLISTERS",
                label_de="Blasen",
                label_en="Blisters",
                label_pl="Pęcherze",
            ),
            _opt(
                "OOZING",
                label_de="Nässen",
                label_en="Oozing",
                label_pl="Sączenie",
            ),
            NONE,
        ],
    ),
    _q(
        "Q064",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=4040,
        text_de="Treten Fieber oder allgemeines Unwohlsein auf?",
        text_en="Are fever or general malaise present?",
        text_pl="Czy występuje gorączka lub złe samopoczucie?",
        options=[
            _opt("FEVER", label_de="Fieber", label_en="Fever", label_pl="Gorączka"),
            _opt(
                "WEAKNESS",
                label_de="Schwäche",
                label_en="Weakness",
                label_pl="Osłabienie",
            ),
            _opt(
                "MUSCLE_PAIN",
                label_de="Muskelschmerzen",
                label_en="Muscle pain",
                label_pl="Bóle mięśni",
            ),
            NONE,
        ],
    ),
    _q(
        "Q065",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=4050,
        text_de="Sind Mund, Augen oder andere Schleimhäute betroffen?",
        text_en="Are the mouth, eyes, or other mucous membranes affected?",
        text_pl="Czy zmiany dotyczą ust, oczu lub innych błon śluzowych?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q066",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=4060,
        text_de="Wurde in den letzten 4 Wochen ein neues Medikament oder Nahrungsergänzungsmittel begonnen?",
        text_en="Was a new medication or supplement started in the last 4 weeks?",
        text_pl="Czy w ostatnich 4 tygodniach rozpoczęto nowy lek lub suplement?",
        options=YES_NO,
    ),
    _ft(
        "Q066a",
        path_code=PATH_CODE,
        display_order=4065,
        text_de="Welches Medikament / Nahrungsergänzungsmittel und seit wann?",
        text_en="Which medication or supplement, and since when?",
        text_pl="Jaki lek / suplement i od kiedy?",
        show_if={"question_id": "Q066", "op": "eq", "value": "YES"},
    ),
    _q(
        "Q067",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=4070,
        text_de="Wurde ein neues Kosmetik-, Reinigungs- oder Hautpflegeprodukt verwendet?",
        text_en="Was a new cosmetic, detergent, or skin care product used?",
        text_pl="Czy użyto nowego kosmetyku, detergentu lub produktu do skóry?",
        options=YES_NO,
    ),
    _ft(
        "Q067a",
        path_code=PATH_CODE,
        display_order=4075,
        text_de="Welches Produkt?",
        text_en="Which product?",
        text_pl="Jakiego produktu?",
        show_if={"question_id": "Q067", "op": "eq", "value": "YES"},
    ),
    _q(
        "Q068",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=4080,
        text_de="Hat jemand aus Ihrem engen Umfeld ähnliche Symptome?",
        text_en="Does anyone close to you have similar symptoms?",
        text_pl="Czy ktoś z bliskiego otoczenia ma podobne objawy?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q069",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=4090,
        text_de="Hatten Sie früher schon einen ähnlichen Ausschlag?",
        text_en="Have you had a similar rash before?",
        text_pl="Czy podobna wysypka występowała wcześniej?",
        options=YES_NO,
    ),
    _q(
        "Q070",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=4100,
        text_de="Was wurde bisher angewendet?",
        text_en="What has been used so far?",
        text_pl="Co było dotychczas stosowane?",
        options=[
            NONE,
            _opt(
                "OTC_CREAM",
                label_de="OTC-Creme",
                label_en="OTC cream",
                label_pl="Krem OTC",
            ),
            _opt(
                "PRESCRIPTION_MEDICATION",
                label_de="Verschreibungspflichtiges Medikament",
                label_en="Prescription medication",
                label_pl="Lek na receptę",
            ),
            _opt(
                "ANTIHISTAMINE",
                label_de="Antihistaminikum",
                label_en="Antihistamine",
                label_pl="Antyhistaminowy",
            ),
            _opt(
                "STEROID",
                label_de="Steroid",
                label_en="Steroid",
                label_pl="Steroid",
            ),
            _opt(
                "ANTIBIOTIC",
                label_de="Antibiotikum",
                label_en="Antibiotic",
                label_pl="Antybiotyk",
            ),
            OTHER,
        ],
    ),
    _q(
        "Q071",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=4110,
        text_de="Sind Sie schwanger?",
        text_en="Are you pregnant?",
        text_pl="Czy jest Pani w ciąży?",
        options=PREGNANCY,
    ),
]
