"""Seed questions for CCE-015 – follow-up visit (Q280–Q288, Q287a)."""

from __future__ import annotations

from typing import Any

from apps.telederm.models import TeledermAnswerType, TeledermSection
from apps.telederm.seed.helpers import (
    NO,
    NOT_APPLICABLE,
    OTHER,
    YES,
    YES_NO,
    _ft,
    _opt,
    _q,
)

PATH_CODE = "CCE-015"
BASE_ORDER = 15000

CCE015_CATALOG: list[dict[str, Any]] = [
    _q(
        "Q280",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER,
        text_de="Worum handelt es sich bei der Kontrolle?",
        text_en="What is the follow-up visit for?",
        text_pl="Czego dotyczy kontrola?",
        options=[
            _opt("MOLE", label_de="Muttermal", label_en="Mole", label_pl="Znamię"),
            _opt(
                "OTHER_SKIN_LESION",
                label_de="Andere Hautveränderung",
                label_en="Other skin lesion",
                label_pl="Inna zmiana skórna",
            ),
            _opt("RASH", label_de="Ausschlag", label_en="Rash", label_pl="Wysypka"),
            _opt("ACNE", label_de="Akne", label_en="Acne", label_pl="Trądzik"),
            _opt("HAIR", label_de="Haare", label_en="Hair", label_pl="Włosy"),
            _opt("NAILS", label_de="Nägel", label_en="Nails", label_pl="Paznokcie"),
            _opt(
                "AFTER_TREATMENT_PROCEDURE",
                label_de="Nach Behandlung / Eingriff",
                label_en="After treatment / procedure",
                label_pl="Po leczeniu / zabiegu",
            ),
            OTHER,
        ],
    ),
    _q(
        "Q281",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 10,
        text_de="Wann fand die letzte Beurteilung statt?",
        text_en="When was the previous assessment?",
        text_pl="Kiedy odbyła się poprzednia ocena?",
        options=[
            _opt(
                "UNDER_ONE_MONTH",
                label_de="Weniger als 1 Monat",
                label_en="Less than 1 month",
                label_pl="Mniej niż 1 mies.",
            ),
            _opt(
                "ONE_TO_THREE_MONTHS",
                label_de="1–3 Monate",
                label_en="1–3 months",
                label_pl="1–3 mies.",
            ),
            _opt(
                "THREE_TO_SIX_MONTHS",
                label_de="3–6 Monate",
                label_en="3–6 months",
                label_pl="3–6 mies.",
            ),
            _opt(
                "SIX_TO_TWELVE_MONTHS",
                label_de="6–12 Monate",
                label_en="6–12 months",
                label_pl="6–12 mies.",
            ),
            _opt(
                "OVER_ONE_YEAR",
                label_de="Länger als 1 Jahr",
                label_en="More than 1 year",
                label_pl="Ponad 1 rok",
            ),
        ],
    ),
    _q(
        "Q282",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 20,
        text_de="Liegt ein früherer Befund oder Fotos vor?",
        text_en="Do you have a previous report or photos?",
        text_pl="Czy posiada Pan/Pani poprzedni raport lub zdjęcia?",
        options=YES_NO,
    ),
    _q(
        "Q283",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=BASE_ORDER + 30,
        text_de="Welche Empfehlung wurde damals gegeben?",
        text_en="What recommendation was given previously?",
        text_pl="Jakie było poprzednie zalecenie?",
        options=[
            _opt(
                "OBSERVATION",
                label_de="Beobachtung",
                label_en="Observation",
                label_pl="Obserwacja",
            ),
            _opt(
                "FOLLOW_UP",
                label_de="Kontrolle",
                label_en="Follow-up",
                label_pl="Kontrola",
            ),
            _opt(
                "TREATMENT",
                label_de="Behandlung",
                label_en="Treatment",
                label_pl="Leczenie",
            ),
            _opt(
                "REMOVAL",
                label_de="Entfernung",
                label_en="Removal",
                label_pl="Usunięcie",
            ),
            _opt(
                "ADDITIONAL_TEST",
                label_de="Zusätzliche Untersuchung",
                label_en="Additional test",
                label_pl="Badanie dodatkowe",
            ),
            _opt(
                "DONT_REMEMBER",
                label_de="Erinnere mich nicht",
                label_en="Don't remember",
                label_pl="Nie pamiętam",
            ),
        ],
    ),
    _q(
        "Q284",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=BASE_ORDER + 40,
        text_de="Was hat sich seit der letzten Beurteilung verändert?",
        text_en="What has changed since the last assessment?",
        text_pl="Co zmieniło się od ostatniej oceny?",
        options=[
            _opt(
                "IMPROVEMENT",
                label_de="Besserung",
                label_en="Improvement",
                label_pl="Poprawa",
            ),
            _opt(
                "WORSENING",
                label_de="Verschlechterung",
                label_en="Worsening",
                label_pl="Pogorszenie",
            ),
            _opt("LARGER", label_de="Größer", label_en="Larger", label_pl="Większe"),
            _opt(
                "SMALLER",
                label_de="Kleiner",
                label_en="Smaller",
                label_pl="Mniejsze",
            ),
            _opt(
                "COLOR_CHANGE",
                label_de="Farbveränderung",
                label_en="Color change",
                label_pl="Zmiana koloru",
            ),
            _opt(
                "NEW_SYMPTOMS",
                label_de="Neue Symptome",
                label_en="New symptoms",
                label_pl="Nowe objawy",
            ),
            _opt(
                "NO_CHANGE",
                label_de="Keine Veränderung",
                label_en="No change",
                label_pl="Bez zmian",
            ),
        ],
    ),
    _q(
        "Q285",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=BASE_ORDER + 50,
        text_de="Sind neue Symptome aufgetreten?",
        text_en="Have new symptoms appeared?",
        text_pl="Czy pojawiły się nowe objawy?",
        options=[
            _opt("PAIN", label_de="Schmerz", label_en="Pain", label_pl="Ból"),
            _opt("ITCHING", label_de="Juckreiz", label_en="Itching", label_pl="Świąd"),
            _opt(
                "BLEEDING",
                label_de="Blutung",
                label_en="Bleeding",
                label_pl="Krwawienie",
            ),
            _opt("OOZING", label_de="Nässen", label_en="Oozing", label_pl="Sączenie"),
            _opt("FEVER", label_de="Fieber", label_en="Fever", label_pl="Gorączka"),
            OTHER,
            _opt("NONE", label_de="Keine", label_en="None", label_pl="Brak"),
        ],
    ),
    _q(
        "Q286",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 60,
        text_de="Haben Sie die empfohlene Behandlung angewendet?",
        text_en="Did you follow the recommended treatment?",
        text_pl="Czy zastosowano zalecone leczenie?",
        options=[
            _opt(
                "YES_FULLY",
                label_de="Ja, vollständig",
                label_en="Yes, fully",
                label_pl="Tak w całości",
            ),
            _opt(
                "PARTIALLY",
                label_de="Teilweise",
                label_en="Partially",
                label_pl="Częściowo",
            ),
            NO,
            NOT_APPLICABLE,
        ],
    ),
    _q(
        "Q287",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 70,
        text_de="Traten Nebenwirkungen der Behandlung auf?",
        text_en="Did you experience side effects from the treatment?",
        text_pl="Czy wystąpiły działania niepożądane leczenia?",
        options=[YES, NO, NOT_APPLICABLE],
    ),
    _ft(
        "Q287a",
        path_code=PATH_CODE,
        display_order=BASE_ORDER + 75,
        text_de="Welche Nebenwirkungen?",
        text_en="Which side effects?",
        text_pl="Jakie?",
        show_if={"question_id": "Q287", "op": "eq", "value": "YES"},
    ),
    _q(
        "Q288",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=BASE_ORDER + 80,
        text_de="Was erwarten Sie von der heutigen Kontrolle?",
        text_en="What do you expect from today's follow-up visit?",
        text_pl="Czego oczekuje Pan/Pani podczas dzisiejszej kontroli?",
        options=[
            _opt(
                "EFFECT_ASSESSMENT",
                label_de="Beurteilung des Behandlungserfolgs",
                label_en="Assessment of treatment effect",
                label_pl="Ocena efektu",
            ),
            _opt(
                "FURTHER_TREATMENT",
                label_de="Weitere Behandlung",
                label_en="Further treatment",
                label_pl="Dalsze leczenie",
            ),
            _opt(
                "PRESCRIPTION",
                label_de="Rezept",
                label_en="Prescription",
                label_pl="Recepta",
            ),
            _opt(
                "SECOND_OPINION",
                label_de="Zweite Meinung",
                label_en="Second opinion",
                label_pl="Druga opinia",
            ),
            _opt(
                "FURTHER_RECOMMENDATIONS",
                label_de="Weitere Empfehlungen",
                label_en="Further recommendations",
                label_pl="Dalsze zalecenia",
            ),
        ],
    ),
]
