"""Seed data for telederm path CCE-001 (new skin lesion)."""

from __future__ import annotations

from typing import Any

from apps.telederm.models import TeledermAnswerType, TeledermSection
from apps.telederm.seed.helpers import _opt, _q

PATH_CODE = "CCE-001"

CCE001_QUESTIONS: list[dict[str, Any]] = [
    _q(
        "Q001",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=100,
        text_de="Wie viele neue Hautveränderungen haben Sie bemerkt?",
        text_en="How many new skin lesions have you noticed?",
        text_pl="Ile nowych zmian zauważył(a) Pan/Pani?",
        options=[
            _opt("ONE", label_de="1", label_en="1", label_pl="1"),
            _opt("TWO_TO_FIVE", label_de="2–5", label_en="2–5", label_pl="2–5"),
            _opt(
                "MORE_THAN_FIVE",
                label_de="Mehr als 5",
                label_en="More than 5",
                label_pl="Więcej niż 5",
            ),
        ],
    ),
    _q(
        "Q002",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=110,
        text_de="Wo befindet sich die am meisten beunruhigende Veränderung?",
        text_en="Where is the most concerning lesion located?",
        text_pl="Gdzie znajduje się najbardziej niepokojąca zmiana?",
        options=[
            _opt("FACE", label_de="Gesicht", label_en="Face", label_pl="Twarz"),
            _opt(
                "SCALP",
                label_de="Kopfhaut",
                label_en="Scalp",
                label_pl="Skóra głowy",
            ),
            _opt("NECK", label_de="Hals", label_en="Neck", label_pl="Szyja"),
            _opt(
                "CHEST",
                label_de="Brustkorb",
                label_en="Chest",
                label_pl="Klatka piersiowa",
            ),
            _opt("BACK", label_de="Rücken", label_en="Back", label_pl="Plecy"),
            _opt(
                "ABDOMEN",
                label_de="Bauch",
                label_en="Abdomen",
                label_pl="Brzuch",
            ),
            _opt(
                "UPPER_LIMB",
                label_de="Obere Extremität",
                label_en="Upper limb",
                label_pl="Kończyna górna",
            ),
            _opt("HAND", label_de="Hand", label_en="Hand", label_pl="Dłoń"),
            _opt(
                "BUTTOCK",
                label_de="Gesäß",
                label_en="Buttock",
                label_pl="Pośladek",
            ),
            _opt(
                "LOWER_LIMB",
                label_de="Untere Extremität",
                label_en="Lower limb",
                label_pl="Kończyna dolna",
            ),
            _opt("FOOT", label_de="Fuß", label_en="Foot", label_pl="Stopa"),
            _opt(
                "GENITAL_AREA",
                label_de="Intimbereich",
                label_en="Genital area",
                label_pl="Okolica intymna",
            ),
            _opt(
                "MUCOSA",
                label_de="Schleimhaut",
                label_en="Mucosa",
                label_pl="Błona śluzowa",
            ),
            _opt("OTHER", label_de="Sonstiges", label_en="Other", label_pl="Inne"),
        ],
    ),
    _q(
        "Q002a",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.FREE_TEXT,
        display_order=115,
        text_de="Bitte geben Sie die andere Lokalisation an.",
        text_en="Please specify the other location.",
        text_pl="Proszę podać inną lokalizację.",
        show_if={"question_id": "Q002", "op": "contains", "value": "OTHER"},
    ),
    _q(
        "Q003",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=120,
        text_de="Wann haben Sie diese Veränderung zum ersten Mal bemerkt?",
        text_en="When did you first notice this lesion?",
        text_pl="Kiedy po raz pierwszy zauważył(a) Pan/Pani tę zmianę?",
        options=[
            _opt("TODAY", label_de="Heute", label_en="Today", label_pl="Dzisiaj"),
            _opt(
                "TWO_TO_SEVEN_DAYS",
                label_de="2–7 Tage",
                label_en="2–7 days",
                label_pl="2–7 dni",
            ),
            _opt(
                "ONE_TO_FOUR_WEEKS",
                label_de="1–4 Wochen",
                label_en="1–4 weeks",
                label_pl="1–4 tygodnie",
            ),
            _opt(
                "ONE_TO_SIX_MONTHS",
                label_de="1–6 Monate",
                label_en="1–6 months",
                label_pl="1–6 miesięcy",
            ),
            _opt(
                "OVER_SIX_MONTHS",
                label_de="Länger als 6 Monate",
                label_en="More than 6 months",
                label_pl="Ponad 6 miesięcy",
            ),
            _opt(
                "UNKNOWN",
                label_de="Weiß nicht",
                label_en="Don't know",
                label_pl="Nie wiem",
            ),
        ],
    ),
    _q(
        "Q004",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=130,
        text_de="Was hat sich seit dem ersten Bemerken verändert?",
        text_en="What has changed since you first noticed it?",
        text_pl="Co zmieniło się od momentu zauważenia?",
        options=[
            _opt(
                "ENLARGING",
                label_de="Vergrößert sich",
                label_en="Enlarging",
                label_pl="Powiększa się",
            ),
            _opt(
                "COLOR_CHANGE",
                label_de="Farbe verändert",
                label_en="Color changed",
                label_pl="Zmieniła kolor",
            ),
            _opt(
                "SHAPE_CHANGE",
                label_de="Form verändert",
                label_en="Shape changed",
                label_pl="Zmieniła kształt",
            ),
            _opt(
                "BECAME_RAISED",
                label_de="Wurde erhaben",
                label_en="Became raised",
                label_pl="Stała się wypukła",
            ),
            _opt(
                "SPREADING",
                label_de="Breitet sich aus",
                label_en="Spreading",
                label_pl="Rozprzestrzenia się",
            ),
            _opt(
                "NO_CHANGE",
                label_de="Keine Veränderung",
                label_en="No change",
                label_pl="Bez zmian",
            ),
            _opt(
                "UNKNOWN",
                label_de="Weiß nicht",
                label_en="Don't know",
                label_pl="Nie wiem",
            ),
        ],
    ),
    _q(
        "Q005",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=140,
        text_de="Welche Symptome treten auf?",
        text_en="What symptoms are present?",
        text_pl="Jakie objawy towarzyszą zmianie?",
        options=[
            _opt("ITCH", label_de="Juckreiz", label_en="Itch", label_pl="Świąd"),
            _opt("PAIN", label_de="Schmerzen", label_en="Pain", label_pl="Ból"),
            _opt(
                "BURNING",
                label_de="Brennen",
                label_en="Burning",
                label_pl="Pieczenie",
            ),
            _opt(
                "TENDERNESS",
                label_de="Druckempfindlichkeit",
                label_en="Tenderness",
                label_pl="Tkliwość",
            ),
            _opt(
                "BLEEDING",
                label_de="Blutung",
                label_en="Bleeding",
                label_pl="Krwawienie",
            ),
            _opt(
                "OOZING",
                label_de="Nässen",
                label_en="Oozing",
                label_pl="Sączenie",
            ),
            _opt(
                "SCALING",
                label_de="Schuppung",
                label_en="Scaling",
                label_pl="Łuszczenie",
            ),
            _opt("CRUST", label_de="Kruste", label_en="Crust", label_pl="Strup"),
            _opt(
                "BLISTER",
                label_de="Blase",
                label_en="Blister",
                label_pl="Pęcherz",
            ),
            _opt("NONE", label_de="Keine", label_en="None", label_pl="Brak"),
        ],
    ),
    _q(
        "Q006",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=150,
        text_de="Ist die Veränderung nach einem bestimmten Ereignis aufgetreten?",
        text_en="Did the lesion appear after a specific event?",
        text_pl="Czy zmiana pojawiła się po konkretnym zdarzeniu?",
        options=[
            _opt("TRAUMA", label_de="Trauma", label_en="Trauma", label_pl="Uraz"),
            _opt("BITE", label_de="Biss", label_en="Bite", label_pl="Ukąszenie"),
            _opt(
                "SUN_OR_BURN",
                label_de="Sonne / Sonnenbrand",
                label_en="Sun / sunburn",
                label_pl="Słońce / oparzenie",
            ),
            _opt(
                "NEW_COSMETIC",
                label_de="Neues Kosmetikprodukt",
                label_en="New cosmetic product",
                label_pl="Nowy kosmetyk",
            ),
            _opt(
                "NEW_MEDICATION",
                label_de="Neues Medikament",
                label_en="New medication",
                label_pl="Nowy lek",
            ),
            _opt(
                "PLANT_OR_CHEMICAL_CONTACT",
                label_de="Kontakt mit Pflanze / Chemikalien",
                label_en="Contact with plant / chemicals",
                label_pl="Kontakt z rośliną / chemikaliami",
            ),
            _opt("NONE", label_de="Keines", label_en="None", label_pl="Brak"),
            _opt(
                "UNKNOWN",
                label_de="Weiß nicht",
                label_en="Don't know",
                label_pl="Nie wiem",
            ),
        ],
    ),
    _q(
        "Q007",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=160,
        text_de="Wurde die Veränderung bereits von einem Arzt beurteilt?",
        text_en="Has a doctor already assessed this lesion?",
        text_pl="Czy zmiana była wcześniej oceniana przez lekarza?",
        options=[
            _opt("YES", label_de="Ja", label_en="Yes", label_pl="Tak"),
            _opt("NO", label_de="Nein", label_en="No", label_pl="Nie"),
        ],
    ),
    _q(
        "Q007a",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=165,
        text_de="Welche Empfehlung wurde gegeben?",
        text_en="What recommendation was given?",
        text_pl="Jakie było zalecenie?",
        show_if={"question_id": "Q007", "op": "eq", "value": "YES"},
        options=[
            _opt(
                "OBSERVATION",
                label_de="Beobachtung",
                label_en="Observation",
                label_pl="Obserwacja",
            ),
            _opt(
                "FOLLOW_UP",
                label_de="Kontrolle",
                label_en="Follow-up visit",
                label_pl="Kontrola",
            ),
            _opt(
                "REMOVAL",
                label_de="Entfernung",
                label_en="Removal",
                label_pl="Usunięcie",
            ),
            _opt(
                "TREATMENT",
                label_de="Behandlung",
                label_en="Treatment",
                label_pl="Leczenie",
            ),
            _opt(
                "DONT_REMEMBER",
                label_de="Erinnere mich nicht",
                label_en="Don't remember",
                label_pl="Nie pamiętam",
            ),
        ],
    ),
    _q(
        "Q008",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=170,
        text_de="Hatten Sie früher schon eine ähnliche Veränderung?",
        text_en="Have you had a similar lesion before?",
        text_pl="Czy wcześniej występowała podobna zmiana?",
        options=[
            _opt("YES", label_de="Ja", label_en="Yes", label_pl="Tak"),
            _opt("NO", label_de="Nein", label_en="No", label_pl="Nie"),
            _opt(
                "UNKNOWN",
                label_de="Weiß nicht",
                label_en="Don't know",
                label_pl="Nie wiem",
            ),
        ],
    ),
    _q(
        "Q009",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=180,
        text_de="Gab es bei Ihnen oder in Ihrer Familie Hautkrebs / Melanom?",
        text_en="Have you or a close family member had skin cancer / melanoma?",
        text_pl="Czy u Pana/Pani lub w rodzinie występował rak skóry / czerniak?",
        options=[
            _opt("IN_ME", label_de="Bei mir", label_en="In me", label_pl="U mnie"),
            _opt(
                "IN_FAMILY",
                label_de="In der Familie",
                label_en="In the family",
                label_pl="W rodzinie",
            ),
            _opt("NO", label_de="Nein", label_en="No", label_pl="Nie"),
            _opt(
                "UNKNOWN",
                label_de="Weiß nicht",
                label_en="Don't know",
                label_pl="Nie wiem",
            ),
        ],
    ),
    _q(
        "Q010",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=190,
        text_de="Besteht eine Immunschwäche?",
        text_en="Is there immunosuppression?",
        text_pl="Czy występuje osłabienie odporności?",
        options=[
            _opt("NO", label_de="Nein", label_en="No", label_pl="Nie"),
            _opt(
                "IMMUNOSUPPRESSANTS",
                label_de="Immunsuppressiva",
                label_en="Immunosuppressants",
                label_pl="Leki immunosupresyjne",
            ),
            _opt(
                "POST_TRANSPLANT",
                label_de="Nach Organtransplantation",
                label_en="After organ transplant",
                label_pl="Po przeszczepie",
            ),
            _opt(
                "ONCOLOGY_THERAPY",
                label_de="Onkologische Therapie",
                label_en="Oncology therapy",
                label_pl="Terapia onkologiczna",
            ),
            _opt("HIV", label_de="HIV", label_en="HIV", label_pl="HIV"),
            _opt("OTHER", label_de="Sonstiges", label_en="Other", label_pl="Inne"),
            _opt(
                "UNKNOWN",
                label_de="Weiß nicht",
                label_en="Don't know",
                label_pl="Nie wiem",
            ),
        ],
    ),
    _q(
        "Q011",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=200,
        text_de="Was erwarten Sie von der Konsultation?",
        text_en="What do you expect from the consultation?",
        text_pl="Czego oczekuje Pan/Pani od konsultacji?",
        options=[
            _opt(
                "LESION_ASSESSMENT",
                label_de="Beurteilung der Veränderung",
                label_en="Assessment of the lesion",
                label_pl="Ocena zmiany",
            ),
            _opt(
                "TREATMENT",
                label_de="Behandlung",
                label_en="Treatment",
                label_pl="Leczenie",
            ),
            _opt(
                "PRESCRIPTION_IF_INDICATED",
                label_de="Rezept, falls angezeigt",
                label_en="Prescription if indicated",
                label_pl="Recepta, jeśli wskazana",
            ),
            _opt(
                "SECOND_OPINION",
                label_de="Zweite Meinung",
                label_en="Second opinion",
                label_pl="Druga opinia",
            ),
            _opt(
                "FURTHER_RECOMMENDATIONS",
                label_de="Weitere Empfehlungen",
                label_en="Further recommendations",
                label_pl="Dalsze zalecenia",
            ),
        ],
    ),
    _q(
        "Q012",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.FREE_TEXT,
        display_order=210,
        text_de="Zusätzliche Information für den Arzt.",
        text_en="Additional information for the doctor.",
        text_pl="Dodatkowa informacja dla lekarza.",
        is_required=False,
    ),
]
