"""Seed questions for telederm path CCE-007 (skin flaking)."""

from __future__ import annotations

from typing import Any

from apps.telederm.models import TeledermAnswerType, TeledermSection
from apps.telederm.seed.helpers import (
    DURATION_UNDER_SEVEN,
    NO,
    OTHER,
    YES,
    YES_NO,
    YES_NO_UNKNOWN,
    _opt,
    _q,
)

CCE007_QUESTIONS: list[dict[str, Any]] = [
    _q(
        "Q120",
        path_code="CCE-007",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=7000,
        text_de="Wo schuppt sich die Haut?",
        text_en="Where is the skin flaking?",
        text_pl="Gdzie skóra się łuszczy?",
        options=[
            _opt(
                "SCALP",
                label_de="Kopfhaut",
                label_en="Scalp",
                label_pl="Skóra głowy",
            ),
            _opt("FACE", label_de="Gesicht", label_en="Face", label_pl="Twarz"),
            _opt("EARS", label_de="Ohren", label_en="Ears", label_pl="Uszy"),
            _opt(
                "CHEST",
                label_de="Brustkorb",
                label_en="Chest",
                label_pl="Klatka",
            ),
            _opt("BACK", label_de="Rücken", label_en="Back", label_pl="Plecy"),
            _opt("ELBOWS", label_de="Ellbogen", label_en="Elbows", label_pl="Łokcie"),
            _opt("KNEES", label_de="Knie", label_en="Knees", label_pl="Kolana"),
            _opt("HANDS", label_de="Hände", label_en="Hands", label_pl="Dłonie"),
            _opt("FEET", label_de="Füße", label_en="Feet", label_pl="Stopy"),
            OTHER,
        ],
    ),
    _q(
        "Q121",
        path_code="CCE-007",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=7010,
        text_de="Seit wann?",
        text_en="Since when?",
        text_pl="Od kiedy?",
        options=DURATION_UNDER_SEVEN,
    ),
    _q(
        "Q122",
        path_code="CCE-007",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=7020,
        text_de="Begleitet die Schuppung eine Rötung?",
        text_en="Is the flaking accompanied by redness?",
        text_pl="Czy łuszczeniu towarzyszy zaczerwienienie?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q123",
        path_code="CCE-007",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=7030,
        text_de="Juckt es?",
        text_en="Does it itch?",
        text_pl="Czy swędzi?",
        options=YES_NO,
    ),
    _q(
        "Q124",
        path_code="CCE-007",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=7040,
        text_de="Treten Risse, Blutungen oder Nässen auf?",
        text_en="Are there cracks, bleeding, or oozing?",
        text_pl="Czy występują pęknięcia, krwawienie lub sączenie?",
        options=[
            _opt(
                "CRACKS",
                label_de="Risse",
                label_en="Cracks",
                label_pl="Pęknięcia",
            ),
            _opt(
                "BLEEDING",
                label_de="Blutungen",
                label_en="Bleeding",
                label_pl="Krwawienie",
            ),
            _opt(
                "OOZING",
                label_de="Nässen",
                label_en="Oozing",
                label_pl="Sączenie",
            ),
            NO,
        ],
    ),
    _q(
        "Q125",
        path_code="CCE-007",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=7050,
        text_de="Ist das Problem saisonal oder wiederkehrend?",
        text_en="Is the problem seasonal or recurring?",
        text_pl="Czy problem jest sezonowy lub nawracający?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q126",
        path_code="CCE-007",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=7060,
        text_de="Wurde ein neues Kosmetikum oder Reinigungsmittel verwendet?",
        text_en="Have you used a new cosmetic or detergent?",
        text_pl="Czy używano nowego kosmetyku / detergentu?",
        options=YES_NO,
    ),
    _q(
        "Q127",
        path_code="CCE-007",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=7070,
        text_de="Treten ähnliche Veränderungen bei anderen Haushaltsmitgliedern auf?",
        text_en="Do other household members have similar changes?",
        text_pl="Czy podobne zmiany występują u innych domowników?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q128",
        path_code="CCE-007",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=7080,
        text_de="Welche Behandlung wurde angewendet?",
        text_en="What treatment was used?",
        text_pl="Jakie leczenie stosowano?",
        options=[
            _opt(
                "NOTHING",
                label_de="Nichts",
                label_en="Nothing",
                label_pl="Nic",
            ),
            _opt(
                "EMOLLIENT",
                label_de="Emollient",
                label_en="Emollient",
                label_pl="Emolient",
            ),
            _opt(
                "ANTIFUNGAL",
                label_de="Antimykotikum",
                label_en="Antifungal preparation",
                label_pl="Preparat przeciwgrzybiczy",
            ),
            _opt(
                "STEROID",
                label_de="Steroid",
                label_en="Steroid",
                label_pl="Steroid",
            ),
            OTHER,
        ],
    ),
]
