"""Seed data for telederm path CCE-002 (changing mole)."""

from __future__ import annotations

from typing import Any

from apps.telederm.models import TeledermAnswerType, TeledermSection
from apps.telederm.seed.helpers import (
    NO,
    OTHER,
    UNKNOWN,
    YES_NO,
    YES_NO_UNKNOWN,
    _ft,
    _opt,
    _q,
)

PATH_CODE = "CCE-002"

CCE002_QUESTIONS: list[dict[str, Any]] = [
    _q(
        "Q020",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=2000,
        text_de="Wo befindet sich das Muttermal?",
        text_en="Where is the mole located?",
        text_pl="Gdzie znajduje się znamię?",
        options=[
            _opt("FACE", label_de="Gesicht", label_en="Face", label_pl="Twarz"),
            _opt(
                "SCALP", label_de="Kopfhaut", label_en="Scalp", label_pl="Skóra głowy"
            ),
            _opt("NECK", label_de="Hals", label_en="Neck", label_pl="Szyja"),
            _opt(
                "FRONT_TORSO",
                label_de="Vorderer Rumpf",
                label_en="Front of torso",
                label_pl="Tułów przód",
            ),
            _opt("BACK", label_de="Rücken", label_en="Back", label_pl="Plecy"),
            _opt(
                "UPPER_LIMB",
                label_de="Obere Extremität",
                label_en="Upper limb",
                label_pl="Kończyna górna",
            ),
            _opt("HAND", label_de="Hand", label_en="Hand", label_pl="Dłoń"),
            _opt("BUTTOCK", label_de="Gesäß", label_en="Buttock", label_pl="Pośladek"),
            _opt(
                "LOWER_LIMB",
                label_de="Untere Extremität",
                label_en="Lower limb",
                label_pl="Kończyna dolna",
            ),
            _opt("FOOT", label_de="Fuß", label_en="Foot", label_pl="Stopa"),
            _opt(
                "GENITAL_AREA",
                label_de="Intimbereich",
                label_en="Genital area",
                label_pl="Okolica intymna",
            ),
            OTHER,
        ],
    ),
    _q(
        "Q021",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=2010,
        text_de="Seit wann besteht das Muttermal?",
        text_en="How long has the mole been present?",
        text_pl="Od jak dawna znamię istnieje?",
        options=[
            _opt(
                "UNDER_SIX_MONTHS",
                label_de="Weniger als 6 Monate",
                label_en="Less than 6 months",
                label_pl="Mniej niż 6 miesięcy",
            ),
            _opt(
                "SIX_TO_TWELVE_MONTHS",
                label_de="6–12 Monate",
                label_en="6–12 months",
                label_pl="6–12 miesięcy",
            ),
            _opt(
                "ONE_TO_FIVE_YEARS",
                label_de="1–5 Jahre",
                label_en="1–5 years",
                label_pl="1–5 lat",
            ),
            _opt(
                "OVER_FIVE_YEARS",
                label_de="Länger als 5 Jahre",
                label_en="More than 5 years",
                label_pl="Ponad 5 lat",
            ),
            _opt(
                "SINCE_CHILDHOOD",
                label_de="Seit der Kindheit",
                label_en="Since childhood",
                label_pl="Od dzieciństwa",
            ),
            UNKNOWN,
        ],
    ),
    _q(
        "Q022",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=2020,
        text_de="Wann haben Sie bemerkt, dass es sich zu verändern begann?",
        text_en="When did you notice it started to change?",
        text_pl="Kiedy zauważył(a) Pan/Pani, że zaczęło się zmieniać?",
        options=[
            _opt(
                "UNDER_SEVEN_DAYS",
                label_de="Weniger als 7 Tage",
                label_en="Less than 7 days",
                label_pl="Mniej niż 7 dni",
            ),
            _opt(
                "ONE_TO_FOUR_WEEKS",
                label_de="1–4 Wochen",
                label_en="1–4 weeks",
                label_pl="1–4 tygodnie",
            ),
            _opt(
                "ONE_TO_SIX_MONTHS",
                label_de="1–6 Monate",
                label_en="1–6 months",
                label_pl="1–6 miesięcy",
            ),
            _opt(
                "OVER_SIX_MONTHS",
                label_de="Länger als 6 Monate",
                label_en="More than 6 months",
                label_pl="Ponad 6 miesięcy",
            ),
            UNKNOWN,
        ],
    ),
    _q(
        "Q023",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=2030,
        text_de="Was genau hat sich verändert?",
        text_en="What exactly has changed?",
        text_pl="Co dokładnie się zmieniło?",
        options=[
            _opt("SIZE", label_de="Größe", label_en="Size", label_pl="Wielkość"),
            _opt("COLOR", label_de="Farbe", label_en="Color", label_pl="Kolor"),
            _opt("SHAPE", label_de="Form", label_en="Shape", label_pl="Kształt"),
            _opt(
                "BECAME_RAISED",
                label_de="Wurde erhaben",
                label_en="Became raised",
                label_pl="Stało się wypukłe",
            ),
            _opt(
                "SURFACE",
                label_de="Oberfläche",
                label_en="Surface",
                label_pl="Powierzchnia",
            ),
            _opt(
                "STARTED_BLEEDING",
                label_de="Begann zu bluten",
                label_en="Started bleeding",
                label_pl="Zaczęło krwawić",
            ),
            _opt(
                "ITCH_APPEARED",
                label_de="Juckreiz trat auf",
                label_en="Itch appeared",
                label_pl="Pojawił się świąd",
            ),
            _opt(
                "PAIN_APPEARED",
                label_de="Schmerzen traten auf",
                label_en="Pain appeared",
                label_pl="Pojawił się ból",
            ),
            OTHER,
        ],
    ),
    _ft(
        "Q023a",
        path_code=PATH_CODE,
        display_order=2035,
        text_de="Welche andere Veränderung ist aufgetreten?",
        text_en="What other change occurred?",
        text_pl="Jaka inna zmiana?",
        show_if={"question_id": "Q023", "op": "contains", "value": "OTHER"},
    ),
    _q(
        "Q024",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=2040,
        text_de="Hat das Muttermal ohne Verletzung geblutet?",
        text_en="Has the mole bled without injury?",
        text_pl="Czy znamię krwawiło bez urazu?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q025",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=2050,
        text_de="Wurde es bereits fotografiert oder dermatoskopisch untersucht?",
        text_en="Has it been photographed or examined with dermoscopy?",
        text_pl="Czy było wcześniej fotografowane lub badane dermatoskopowo?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q026",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=2060,
        text_de="Haben Sie einen früheren Befund oder Fotos?",
        text_en="Do you have a previous report or photos?",
        text_pl="Czy ma Pan/Pani poprzedni raport lub zdjęcia?",
        show_if={"question_id": "Q025", "op": "eq", "value": "YES"},
        options=YES_NO,
    ),
    _q(
        "Q027",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=2070,
        text_de="Hat ein Arzt früher eine Kontrolle oder Entfernung empfohlen?",
        text_en="Did a doctor previously recommend follow-up or removal?",
        text_pl="Czy lekarz wcześniej zalecił kontrolę lub usunięcie?",
        options=[
            _opt(
                "FOLLOW_UP",
                label_de="Kontrolle",
                label_en="Follow-up visit",
                label_pl="Kontrola",
            ),
            _opt(
                "REMOVAL",
                label_de="Entfernung",
                label_en="Removal",
                label_pl="Usunięcie",
            ),
            _opt(
                "OBSERVATION",
                label_de="Beobachtung",
                label_en="Observation",
                label_pl="Obserwacja",
            ),
            _opt("NOTHING", label_de="Nichts", label_en="Nothing", label_pl="Nic"),
            _opt(
                "DONT_REMEMBER",
                label_de="Erinnere mich nicht",
                label_en="Don't remember",
                label_pl="Nie pamiętam",
            ),
        ],
    ),
    _q(
        "Q028",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=2080,
        text_de="Haben Sie viele Muttermale?",
        text_en="Do you have many moles?",
        text_pl="Czy ma Pan/Pani wiele znamion?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q029",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=2090,
        text_de="Gab es bei Ihnen oder in Ihrer Familie ein Melanom?",
        text_en="Have you or a family member had melanoma?",
        text_pl="Czy u Pana/Pani lub w rodzinie występował czerniak?",
        options=[
            _opt("IN_ME", label_de="Bei mir", label_en="In me", label_pl="U mnie"),
            _opt(
                "IN_FAMILY",
                label_de="In der Familie",
                label_en="In the family",
                label_pl="W rodzinie",
            ),
            NO,
            UNKNOWN,
        ],
    ),
    _q(
        "Q030",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=2100,
        text_de="Besteht eine Immunschwäche?",
        text_en="Is there immunosuppression?",
        text_pl="Czy występuje osłabienie odporności?",
        options=YES_NO_UNKNOWN,
    ),
    _ft(
        "Q031",
        path_code=PATH_CODE,
        display_order=2110,
        text_de="Zusätzliche Information für den Arzt.",
        text_en="Additional information for the doctor.",
        text_pl="Dodatkowa informacja dla lekarza.",
        is_required=False,
    ),
]
