"""Seed questions for CCE-013 – herpes / cold sore (Q240–Q249)."""

from __future__ import annotations

from typing import Any

from apps.telederm.models import TeledermAnswerType, TeledermSection
from apps.telederm.seed.helpers import (
    NO,
    NOT_APPLICABLE,
    OTHER,
    YES,
    YES_NO,
    YES_NO_UNKNOWN,
    _opt,
    _q,
)

PATH_CODE = "CCE-013"
BASE_ORDER = 13000

CCE013_CATALOG: list[dict[str, Any]] = [
    _q(
        "Q240",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=BASE_ORDER,
        text_de="Wo befinden sich die Bläschen oder Veränderungen?",
        text_en="Where are the blisters or changes located?",
        text_pl="Gdzie znajdują się pęcherzyki / zmiany?",
        options=[
            _opt("LIPS", label_de="Lippen", label_en="Lips", label_pl="Usta"),
            _opt(
                "PERIORAL",
                label_de="Lippenumgebung",
                label_en="Around the lips",
                label_pl="Okolica ust",
            ),
            _opt("NOSE", label_de="Nase", label_en="Nose", label_pl="Nos"),
            _opt("FACE", label_de="Gesicht", label_en="Face", label_pl="Twarz"),
            _opt(
                "GENITALIA",
                label_de="Genitalbereich",
                label_en="Genital area",
                label_pl="Genitalia",
            ),
            _opt("TRUNK", label_de="Rumpf", label_en="Trunk", label_pl="Tułów"),
            OTHER,
        ],
    ),
    _q(
        "Q241",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 10,
        text_de="Seit wann bestehen die Veränderungen?",
        text_en="How long have the changes been present?",
        text_pl="Od kiedy trwa problem?",
        options=[
            _opt(
                "UNDER_24H",
                label_de="Weniger als 24 Stunden",
                label_en="Less than 24 hours",
                label_pl="Mniej niż 24 h",
            ),
            _opt(
                "TWO_TO_THREE_DAYS",
                label_de="2–3 Tage",
                label_en="2–3 days",
                label_pl="2–3 dni",
            ),
            _opt(
                "FOUR_TO_SEVEN_DAYS",
                label_de="4–7 Tage",
                label_en="4–7 days",
                label_pl="4–7 dni",
            ),
            _opt(
                "OVER_SEVEN_DAYS",
                label_de="Länger als 7 Tage",
                label_en="More than 7 days",
                label_pl="Ponad 7 dni",
            ),
        ],
    ),
    _q(
        "Q242",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=BASE_ORDER + 20,
        text_de="Hatten Sie vor dem Auftreten Brennen, Kribbeln oder Schmerzen?",
        text_en="Before the changes appeared, did you have burning, tingling, or pain?",
        text_pl="Czy przed pojawieniem się było pieczenie, mrowienie lub ból?",
        options=[
            _opt(
                "BURNING",
                label_de="Brennen",
                label_en="Burning",
                label_pl="Pieczenie",
            ),
            _opt(
                "TINGLING",
                label_de="Kribbeln",
                label_en="Tingling",
                label_pl="Mrowienie",
            ),
            _opt("PAIN", label_de="Schmerz", label_en="Pain", label_pl="Ból"),
            _opt("NONE", label_de="Nein", label_en="No", label_pl="Nie"),
        ],
    ),
    _q(
        "Q243",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 30,
        text_de="Ist dies der erste solche Vorfall?",
        text_en="Is this the first such episode?",
        text_pl="Czy to pierwszy taki epizod?",
        options=YES_NO,
    ),
    _q(
        "Q244",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 40,
        text_de="Falls wiederkehrend: wie oft tritt es auf?",
        text_en="If recurring: how often does it occur?",
        text_pl="Jeżeli nawraca: jak często?",
        show_if={"question_id": "Q243", "op": "eq", "value": "NO"},
        options=[
            _opt(
                "UNDER_ONCE_YEAR",
                label_de="Weniger als 1× pro Jahr",
                label_en="Less than once a year",
                label_pl="Mniej niż 1/rok",
            ),
            _opt(
                "ONE_TO_THREE_YEAR",
                label_de="1–3× pro Jahr",
                label_en="1–3 times a year",
                label_pl="1–3/rok",
            ),
            _opt(
                "OVER_THREE_YEAR",
                label_de="Mehr als 3× pro Jahr",
                label_en="More than 3 times a year",
                label_pl="Ponad 3/rok",
            ),
        ],
    ),
    _q(
        "Q245",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 50,
        text_de="Bestehen Fieber oder ein allgemeines Unwohlsein?",
        text_en="Do you have fever or feel generally unwell?",
        text_pl="Czy występuje gorączka lub złe samopoczucie?",
        options=YES_NO,
    ),
    _q(
        "Q246",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 60,
        text_de="Betreffen die Veränderungen das Auge oder die unmittelbare Augenumgebung?",
        text_en="Do the changes affect the eye or the immediate area around the eye?",
        text_pl="Czy zmiany dotyczą oka lub bezpośredniego sąsiedztwa oka?",
        options=YES_NO,
    ),
    _q(
        "Q247",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 70,
        text_de="Sind Sie schwanger?",
        text_en="Are you pregnant?",
        text_pl="Czy jest Pani w ciąży?",
        options=[YES, NO, NOT_APPLICABLE],
    ),
    _q(
        "Q248",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 80,
        text_de="Besteht eine Immunsuppression?",
        text_en="Do you have immunosuppression?",
        text_pl="Czy występuje immunosupresja?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q249",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 90,
        text_de="Wurde bereits eine antivirale Behandlung angewendet?",
        text_en="Have you already used antiviral treatment?",
        text_pl="Czy stosowano już leczenie przeciwwirusowe?",
        options=YES_NO,
    ),
]
