"""Seed questions for telederm path CCE-008 (acne / pimples)."""

from __future__ import annotations

from typing import Any

from apps.telederm.models import TeledermAnswerType, TeledermSection
from apps.telederm.seed.helpers import (
    NOT_APPLICABLE,
    NO,
    NONE,
    OTHER,
    UNKNOWN,
    YES,
    YES_NO,
    YES_NO_UNKNOWN,
    _ft,
    _opt,
    _q,
)

CCE008_QUESTIONS: list[dict[str, Any]] = [
    _q(
        "Q140",
        path_code="CCE-008",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=8000,
        text_de="Wo treten die Veränderungen auf?",
        text_en="Where do the lesions occur?",
        text_pl="Gdzie występują zmiany?",
        options=[
            _opt(
                "FOREHEAD",
                label_de="Stirn",
                label_en="Forehead",
                label_pl="Czoło",
            ),
            _opt("CHEEKS", label_de="Wangen", label_en="Cheeks", label_pl="Policzki"),
            _opt("CHIN", label_de="Kinn", label_en="Chin", label_pl="Broda"),
            _opt(
                "FULL_FACE",
                label_de="Ganzes Gesicht",
                label_en="Entire face",
                label_pl="Cała twarz",
            ),
            _opt(
                "CHEST",
                label_de="Brustkorb",
                label_en="Chest",
                label_pl="Klatka",
            ),
            _opt("BACK", label_de="Rücken", label_en="Back", label_pl="Plecy"),
            _opt(
                "SHOULDERS",
                label_de="Schultern",
                label_en="Shoulders",
                label_pl="Ramiona",
            ),
            OTHER,
        ],
    ),
    _q(
        "Q141",
        path_code="CCE-008",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=8010,
        text_de="Seit wann besteht das Problem?",
        text_en="How long has the problem been present?",
        text_pl="Od kiedy trwa problem?",
        options=[
            _opt(
                "UNDER_ONE_MONTH",
                label_de="Weniger als 1 Monat",
                label_en="Less than 1 month",
                label_pl="<1 mies.",
            ),
            _opt(
                "ONE_TO_SIX_MONTHS",
                label_de="1–6 Monate",
                label_en="1–6 months",
                label_pl="1–6 mies.",
            ),
            _opt(
                "SIX_TO_TWELVE_MONTHS",
                label_de="6–12 Monate",
                label_en="6–12 months",
                label_pl="6–12 mies.",
            ),
            _opt(
                "OVER_ONE_YEAR",
                label_de="Länger als 1 Jahr",
                label_en="More than 1 year",
                label_pl=">1 rok",
            ),
        ],
    ),
    _q(
        "Q142",
        path_code="CCE-008",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=8020,
        text_de="Wie sehen die Veränderungen aus Ihrer Sicht aus?",
        text_en="How do the lesions look to you?",
        text_pl="Jak wyglądają zmiany według Pana/Pani?",
        options=[
            _opt(
                "BLACKHEADS",
                label_de="Mitesser",
                label_en="Blackheads",
                label_pl="Zaskórniki",
            ),
            _opt(
                "RED_PIMPLES",
                label_de="Rote Pickel",
                label_en="Red pimples",
                label_pl="Czerwone krostki",
            ),
            _opt(
                "PUSTULES",
                label_de="Eitrige Pickel",
                label_en="Pustules",
                label_pl="Ropne krostki",
            ),
            _opt(
                "PAINFUL_NODULES",
                label_de="Schmerzhafte Knoten",
                label_en="Painful nodules",
                label_pl="Bolesne guzki",
            ),
            _opt("SCARS", label_de="Narben", label_en="Scars", label_pl="Blizny"),
            _opt(
                "DISCOLORATION",
                label_de="Verfärbungen",
                label_en="Discoloration",
                label_pl="Przebarwienia",
            ),
            UNKNOWN,
        ],
    ),
    _q(
        "Q143",
        path_code="CCE-008",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=8030,
        text_de="Sind die Veränderungen schmerzhaft?",
        text_en="Are the lesions painful?",
        text_pl="Czy zmiany są bolesne?",
        options=YES_NO,
    ),
    _q(
        "Q144",
        path_code="CCE-008",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=8040,
        text_de="Bleiben Narben zurück?",
        text_en="Do scars remain?",
        text_pl="Czy zostają blizny?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q145",
        path_code="CCE-008",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=8050,
        text_de="Wurde das Problem früher behandelt?",
        text_en="Has the problem been treated before?",
        text_pl="Czy wcześniej leczono problem?",
        options=YES_NO,
    ),
    _ft(
        "Q145a",
        path_code="CCE-008",
        display_order=8055,
        text_de="Welche Behandlung und mit welchem Effekt?",
        text_en="What treatment and with what effect?",
        text_pl="Jakie leczenie i z jakim efektem?",
        show_if={"question_id": "Q145", "op": "eq", "value": "YES"},
    ),
    _q(
        "Q146",
        path_code="CCE-008",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=8060,
        text_de="Nehmen Sie hormonelle Medikamente / Antibabypille ein?",
        text_en="Are you taking hormonal medications / contraception?",
        text_pl="Czy stosowane są leki hormonalne / antykoncepcja?",
        options=[YES, NO, NOT_APPLICABLE],
    ),
    _q(
        "Q147",
        path_code="CCE-008",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=8070,
        text_de="Sind Sie schwanger oder planen Sie eine Schwangerschaft?",
        text_en="Are you pregnant or planning a pregnancy?",
        text_pl="Czy jest Pani w ciąży lub planuje ciążę?",
        options=[
            _opt(
                "PREGNANT",
                label_de="Schwanger",
                label_en="Pregnant",
                label_pl="Ciąża",
            ),
            _opt(
                "PLANNING",
                label_de="Plane Schwangerschaft",
                label_en="Planning pregnancy",
                label_pl="Planuję",
            ),
            NO,
            NOT_APPLICABLE,
        ],
    ),
    _q(
        "Q148",
        path_code="CCE-008",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=8080,
        text_de="Stellen Sie einen Zusammenhang mit Zyklus, Stress oder Kosmetika fest?",
        text_en="Do you notice a link with your cycle, stress, or cosmetics?",
        text_pl="Czy zauważa Pan/Pani związek z cyklem, stresem lub kosmetykami?",
        options=[
            _opt(
                "MENSTRUAL_CYCLE",
                label_de="Zyklus",
                label_en="Menstrual cycle",
                label_pl="Cykl",
            ),
            _opt("STRESS", label_de="Stress", label_en="Stress", label_pl="Stres"),
            _opt(
                "COSMETICS",
                label_de="Kosmetika",
                label_en="Cosmetics",
                label_pl="Kosmetyki",
            ),
            NONE,
            UNKNOWN,
        ],
    ),
]
