"""Seed data for telederm path CCE-005 (skin itch)."""

from __future__ import annotations

from typing import Any

from apps.telederm.models import TeledermAnswerType, TeledermSection
from apps.telederm.seed.helpers import (
    NONE,
    NO,
    PREGNANCY,
    UNKNOWN,
    YES,
    YES_NO,
    YES_NO_UNKNOWN,
    _ft,
    _opt,
    _q,
)

PATH_CODE = "CCE-005"

CCE005_QUESTIONS: list[dict[str, Any]] = [
    _q(
        "Q080",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=5000,
        text_de="Wo tritt der Juckreiz auf?",
        text_en="Where does the itch occur?",
        text_pl="Gdzie występuje świąd?",
        options=[
            _opt(
                "ONE_AREA",
                label_de="Eine Stelle",
                label_en="One area",
                label_pl="Jedna okolica",
            ),
            _opt("FACE", label_de="Gesicht", label_en="Face", label_pl="Twarz"),
            _opt("SCALP", label_de="Kopfhaut", label_en="Scalp", label_pl="Skóra głowy"),
            _opt("TRUNK", label_de="Rumpf", label_en="Trunk", label_pl="Tułów"),
            _opt("ARMS", label_de="Arme", label_en="Arms", label_pl="Ręce"),
            _opt("HANDS", label_de="Hände", label_en="Hands", label_pl="Dłonie"),
            _opt("LEGS", label_de="Beine", label_en="Legs", label_pl="Nogi"),
            _opt("FEET", label_de="Füße", label_en="Feet", label_pl="Stopy"),
            _opt(
                "GENITAL_AREA",
                label_de="Intimbereich",
                label_en="Genital area",
                label_pl="Okolica intymna",
            ),
            _opt(
                "WHOLE_BODY",
                label_de="Ganzer Körper",
                label_en="Whole body",
                label_pl="Całe ciało",
            ),
        ],
    ),
    _q(
        "Q081",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=5010,
        text_de="Seit wann besteht der Juckreiz?",
        text_en="How long has the itch been present?",
        text_pl="Od kiedy?",
        options=[
            _opt(
                "UNDER_SEVEN_DAYS",
                label_de="Weniger als 7 Tage",
                label_en="Less than 7 days",
                label_pl="Mniej niż 7 dni",
            ),
            _opt(
                "ONE_TO_FOUR_WEEKS",
                label_de="1–4 Wochen",
                label_en="1–4 weeks",
                label_pl="1–4 tygodnie",
            ),
            _opt(
                "ONE_TO_SIX_MONTHS",
                label_de="1–6 Monate",
                label_en="1–6 months",
                label_pl="1–6 miesięcy",
            ),
            _opt(
                "OVER_SIX_MONTHS",
                label_de="Länger als 6 Monate",
                label_en="More than 6 months",
                label_pl="Ponad 6 miesięcy",
            ),
        ],
    ),
    _q(
        "Q082",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=5020,
        text_de="Sind sichtbare Hautveränderungen vorhanden?",
        text_en="Are visible skin changes present?",
        text_pl="Czy widoczne są zmiany skórne?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q083",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=5030,
        text_de="Wann ist der Juckreiz am stärksten?",
        text_en="When is the itch strongest?",
        text_pl="Kiedy świąd jest najsilniejszy?",
        options=[
            _opt(
                "AT_NIGHT",
                label_de="Nachts",
                label_en="At night",
                label_pl="W nocy",
            ),
            _opt(
                "IN_MORNING",
                label_de="Morgens",
                label_en="In the morning",
                label_pl="Rano",
            ),
            _opt(
                "IN_EVENING",
                label_de="Abends",
                label_en="In the evening",
                label_pl="Wieczorem",
            ),
            _opt(
                "AFTER_BATH",
                label_de="Nach dem Baden",
                label_en="After bathing",
                label_pl="Po kąpieli",
            ),
            _opt(
                "AFTER_EXERTION",
                label_de="Nach Anstrengung",
                label_en="After exertion",
                label_pl="Po wysiłku",
            ),
            _opt(
                "CONSTANT",
                label_de="Ständig",
                label_en="Constant",
                label_pl="Stale",
            ),
            _opt(
                "NO_PATTERN",
                label_de="Ohne erkennbares Muster",
                label_en="No clear pattern",
                label_pl="Bez zależności",
            ),
        ],
    ),
    _q(
        "Q084",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=5040,
        text_de="Weckt der Juckreiz Sie nachts?",
        text_en="Does the itch wake you at night?",
        text_pl="Czy świąd budzi w nocy?",
        options=YES_NO,
    ),
    _q(
        "Q085",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=5050,
        text_de="Kratzen sich auch andere Personen im Haushalt / haben Juckreiz?",
        text_en="Do others in your household also scratch or have itch?",
        text_pl="Czy inni domownicy również się drapią / mają świąd?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q086",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=5060,
        text_de="Wurde kürzlich ein neues Medikament, Kosmetikprodukt oder Reinigungsmittel eingeführt?",
        text_en="Was a new medication, cosmetic, or detergent recently introduced?",
        text_pl="Czy ostatnio wprowadzono nowy lek, kosmetyk lub detergent?",
        options=[
            _opt(
                "MEDICATION",
                label_de="Medikament",
                label_en="Medication",
                label_pl="Lek",
            ),
            _opt(
                "COSMETIC",
                label_de="Kosmetikprodukt",
                label_en="Cosmetic",
                label_pl="Kosmetyk",
            ),
            _opt(
                "DETERGENT",
                label_de="Reinigungsmittel",
                label_en="Detergent",
                label_pl="Detergent",
            ),
            NO,
        ],
    ),
    _q(
        "Q087",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=5070,
        text_de="Treten zusätzliche allgemeine Symptome auf?",
        text_en="Are additional general symptoms present?",
        text_pl="Czy występują dodatkowe objawy ogólne?",
        options=[
            _opt("FEVER", label_de="Fieber", label_en="Fever", label_pl="Gorączka"),
            _opt(
                "WEIGHT_LOSS",
                label_de="Gewichtsverlust",
                label_en="Weight loss",
                label_pl="Utrata masy ciała",
            ),
            _opt(
                "NIGHT_SWEATS",
                label_de="Nachtschweiß",
                label_en="Night sweats",
                label_pl="Nocne poty",
            ),
            _opt(
                "JAUNDICE",
                label_de="Gelbsucht",
                label_en="Jaundice",
                label_pl="Żółtaczka",
            ),
            NONE,
        ],
    ),
    _q(
        "Q088",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=5080,
        text_de="Sind Sie schwanger?",
        text_en="Are you pregnant?",
        text_pl="Czy jest Pani w ciąży?",
        options=PREGNANCY,
    ),
    _q(
        "Q089",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=5090,
        text_de="Wurde eine antipruritische Behandlung angewendet?",
        text_en="Has anti-itch treatment been used?",
        text_pl="Czy stosowano leczenie przeciwświądowe?",
        options=YES_NO,
    ),
    _ft(
        "Q089a",
        path_code=PATH_CODE,
        display_order=5095,
        text_de="Was wurde angewendet und mit welchem Effekt?",
        text_en="What was used and with what effect?",
        text_pl="Co stosowano i z jakim efektem?",
        show_if={"question_id": "Q089", "op": "eq", "value": "YES"},
    ),
]
