"""Seed questions for CCE-011 – nail problem (Q200–Q207a)."""

from __future__ import annotations

from typing import Any

from apps.telederm.models import TeledermAnswerType, TeledermSection
from apps.telederm.seed.helpers import (
    NO,
    UNKNOWN,
    YES_NO,
    YES_NO_UNKNOWN,
    _ft,
    _opt,
    _q,
)

PATH_CODE = "CCE-011"
BASE_ORDER = 11000

CCE011_CATALOG: list[dict[str, Any]] = [
    _q(
        "Q200",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=BASE_ORDER,
        text_de="Welche Nägel sind betroffen?",
        text_en="Which nails are affected?",
        text_pl="Których paznokci dotyczy problem?",
        options=[
            _opt(
                "ONE_FINGER_NAIL",
                label_de="1 Fingernagel",
                label_en="1 fingernail",
                label_pl="1 paznokieć dłoni",
            ),
            _opt(
                "SEVERAL_FINGER_NAILS",
                label_de="Mehrere Fingernägel",
                label_en="Several fingernails",
                label_pl="Kilka paznokci dłoni",
            ),
            _opt(
                "ONE_TOE_NAIL",
                label_de="1 Zehennagel",
                label_en="1 toenail",
                label_pl="1 paznokieć stopy",
            ),
            _opt(
                "SEVERAL_TOE_NAILS",
                label_de="Mehrere Zehennägel",
                label_en="Several toenails",
                label_pl="Kilka paznokci stóp",
            ),
            _opt(
                "HANDS_AND_FEET",
                label_de="Hände und Füße",
                label_en="Hands and feet",
                label_pl="Dłonie i stopy",
            ),
        ],
    ),
    _q(
        "Q201",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 10,
        text_de="Seit wann besteht das Problem?",
        text_en="How long has the problem been present?",
        text_pl="Od kiedy trwa problem?",
        options=[
            _opt(
                "UNDER_ONE_MONTH",
                label_de="Weniger als 1 Monat",
                label_en="Less than 1 month",
                label_pl="Mniej niż 1 mies.",
            ),
            _opt(
                "ONE_TO_SIX_MONTHS",
                label_de="1–6 Monate",
                label_en="1–6 months",
                label_pl="1–6 mies.",
            ),
            _opt(
                "OVER_SIX_MONTHS",
                label_de="Länger als 6 Monate",
                label_en="More than 6 months",
                label_pl="Ponad 6 mies.",
            ),
            _opt(
                "OVER_ONE_YEAR",
                label_de="Länger als 1 Jahr",
                label_en="More than 1 year",
                label_pl="Ponad 1 rok",
            ),
        ],
    ),
    _q(
        "Q202",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=BASE_ORDER + 20,
        text_de="Was hat sich verändert?",
        text_en="What has changed?",
        text_pl="Co się zmieniło?",
        options=[
            _opt("COLOR", label_de="Farbe", label_en="Color", label_pl="Kolor"),
            _opt(
                "THICKENING",
                label_de="Verdickung",
                label_en="Thickening",
                label_pl="Pogrubienie",
            ),
            _opt(
                "CRUMBLING",
                label_de="Brüchigkeit",
                label_en="Crumbling",
                label_pl="Kruszenie",
            ),
            _opt(
                "PLATE_SEPARATION",
                label_de="Ablösung der Nagelplatte",
                label_en="Nail plate separation",
                label_pl="Oddzielanie płytki",
            ),
            _opt("RIDGE", label_de="Rille/Grat", label_en="Ridge", label_pl="Prążek"),
            _opt(
                "DEFORMATION",
                label_de="Deformation",
                label_en="Deformation",
                label_pl="Deformacja",
            ),
            _opt("PAIN", label_de="Schmerz", label_en="Pain", label_pl="Ból"),
            _opt(
                "SWELLING_AROUND_NAIL",
                label_de="Schwellung um den Nagel",
                label_en="Swelling around the nail",
                label_pl="Obrzęk wokół paznokcia",
            ),
            _opt(
                "DISCHARGE",
                label_de="Sekretion",
                label_en="Discharge",
                label_pl="Wydzielina",
            ),
        ],
    ),
    _q(
        "Q203",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 30,
        text_de="Gab es ein Trauma?",
        text_en="Was there any trauma?",
        text_pl="Czy był uraz?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q204",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 40,
        text_de="Betrifft die Veränderung nur einen Nagel?",
        text_en="Does the change affect only one nail?",
        text_pl="Czy zmiana dotyczy tylko jednego paznokcia?",
        options=YES_NO,
    ),
    _q(
        "Q205",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=BASE_ORDER + 50,
        text_de="Ist die Haut um den Nagel gerötet oder schmerzhaft?",
        text_en="Is the skin around the nail red or painful?",
        text_pl="Czy skóra wokół jest zaczerwieniona lub bolesna?",
        options=[
            _opt(
                "REDNESS",
                label_de="Rötung",
                label_en="Redness",
                label_pl="Zaczerwienienie",
            ),
            _opt("PAIN", label_de="Schmerz", label_en="Pain", label_pl="Ból"),
            _opt(
                "SWELLING",
                label_de="Schwellung",
                label_en="Swelling",
                label_pl="Obrzęk",
            ),
            _opt(
                "DISCHARGE",
                label_de="Sekretion",
                label_en="Discharge",
                label_pl="Wydzielina",
            ),
            _opt("NONE", label_de="Nein", label_en="No", label_pl="Nie"),
        ],
    ),
    _q(
        "Q206",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 60,
        text_de="Wurde früher eine Nagelpilzerkrankung diagnostiziert?",
        text_en="Has nail fungus been diagnosed before?",
        text_pl="Czy wcześniej rozpoznawano grzybicę paznokci?",
        options=YES_NO,
    ),
    _q(
        "Q207",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=BASE_ORDER + 70,
        text_de="Wurde bereits eine Behandlung durchgeführt?",
        text_en="Has treatment already been applied?",
        text_pl="Czy stosowano leczenie?",
        options=YES_NO,
    ),
    _ft(
        "Q207a",
        path_code=PATH_CODE,
        display_order=BASE_ORDER + 75,
        text_de="Welche Behandlung?",
        text_en="Which treatment?",
        text_pl="Jakie leczenie?",
        show_if={"question_id": "Q207", "op": "eq", "value": "YES"},
    ),
    _q(
        "Q208",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=BASE_ORDER + 80,
        text_de="Leiden Sie an Diabetes oder haben Sie eine Immunschwäche?",
        text_en="Do you have diabetes or immunosuppression?",
        text_pl="Czy choruje Pan/Pani na cukrzycę lub ma obniżoną odporność?",
        options=[
            _opt(
                "DIABETES",
                label_de="Diabetes",
                label_en="Diabetes",
                label_pl="Cukrzyca",
            ),
            _opt(
                "IMMUNOSUPPRESSION",
                label_de="Immunschwäche",
                label_en="Immunosuppression",
                label_pl="Immunosupresja",
            ),
            NO,
            UNKNOWN,
        ],
    ),
]
