"""Seed questions for telederm path CCE-006 (skin redness / face)."""

from __future__ import annotations

from typing import Any

from apps.telederm.models import TeledermAnswerType, TeledermSection
from apps.telederm.seed.helpers import (
    NO,
    NONE,
    OTHER,
    UNKNOWN,
    YES,
    YES_NO,
    _ft,
    _opt,
    _q,
)

CCE006_QUESTIONS: list[dict[str, Any]] = [
    _q(
        "Q100",
        path_code="CCE-006",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=6000,
        text_de="Wo tritt die Rötung auf?",
        text_en="Where does the redness occur?",
        text_pl="Gdzie występuje zaczerwienienie?",
        options=[
            _opt(
                "FULL_FACE",
                label_de="Ganzes Gesicht",
                label_en="Entire face",
                label_pl="Cała twarz",
            ),
            _opt("CHEEKS", label_de="Wangen", label_en="Cheeks", label_pl="Policzki"),
            _opt("NOSE", label_de="Nase", label_en="Nose", label_pl="Nos"),
            _opt(
                "AROUND_EYES",
                label_de="Augenbereich",
                label_en="Around the eyes",
                label_pl="Okolice oczu",
            ),
            _opt(
                "AROUND_MOUTH",
                label_de="Mundbereich",
                label_en="Around the mouth",
                label_pl="Okolice ust",
            ),
            _opt("NECK", label_de="Hals", label_en="Neck", label_pl="Szyja"),
            _opt("TRUNK", label_de="Rumpf", label_en="Trunk", label_pl="Tułów"),
            _opt("LIMBS", label_de="Extremitäten", label_en="Limbs", label_pl="Kończyny"),
            OTHER,
        ],
    ),
    _q(
        "Q101",
        path_code="CCE-006",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=6010,
        text_de="Seit wann?",
        text_en="Since when?",
        text_pl="Od kiedy?",
        options=[
            _opt(
                "UNDER_24_HOURS",
                label_de="Weniger als 24 Stunden",
                label_en="Less than 24 hours",
                label_pl="Mniej niż 24 h",
            ),
            _opt(
                "TWO_TO_SEVEN_DAYS",
                label_de="2–7 Tage",
                label_en="2–7 days",
                label_pl="2–7 dni",
            ),
            _opt(
                "ONE_TO_FOUR_WEEKS",
                label_de="1–4 Wochen",
                label_en="1–4 weeks",
                label_pl="1–4 tyg.",
            ),
            _opt(
                "ONE_TO_SIX_MONTHS",
                label_de="1–6 Monate",
                label_en="1–6 months",
                label_pl="1–6 mies.",
            ),
            _opt(
                "OVER_SIX_MONTHS",
                label_de="Länger als 6 Monate",
                label_en="More than 6 months",
                label_pl=">6 mies.",
            ),
        ],
    ),
    _q(
        "Q102",
        path_code="CCE-006",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=6020,
        text_de="Ist die Rötung dauerhaft oder tritt sie in Schüben auf?",
        text_en="Is the redness constant or does it come and go?",
        text_pl="Czy zaczerwienienie jest stałe czy napadowe?",
        options=[
            _opt(
                "CONSTANT",
                label_de="Dauerhaft",
                label_en="Constant",
                label_pl="Stałe",
            ),
            _opt(
                "PERIODIC",
                label_de="Tritt periodisch auf",
                label_en="Comes and goes",
                label_pl="Pojawia się okresowo",
            ),
            UNKNOWN,
        ],
    ),
    _q(
        "Q103",
        path_code="CCE-006",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=6030,
        text_de="Was verstärkt die Rötung?",
        text_en="What makes the redness worse?",
        text_pl="Co je nasila?",
        options=[
            _opt("SUN", label_de="Sonne", label_en="Sun", label_pl="Słońce"),
            _opt("HEAT", label_de="Wärme", label_en="Heat", label_pl="Ciepło"),
            _opt("COLD", label_de="Kälte", label_en="Cold", label_pl="Zimno"),
            _opt("ALCOHOL", label_de="Alkohol", label_en="Alcohol", label_pl="Alkohol"),
            _opt(
                "SPICY_FOOD",
                label_de="Scharfes Essen",
                label_en="Spicy food",
                label_pl="Ostre jedzenie",
            ),
            _opt("EXERTION", label_de="Anstrengung", label_en="Exertion", label_pl="Wysiłek"),
            _opt("STRESS", label_de="Stress", label_en="Stress", label_pl="Stres"),
            _opt(
                "COSMETICS",
                label_de="Kosmetika",
                label_en="Cosmetics",
                label_pl="Kosmetyki",
            ),
            _opt(
                "NOTHING_NOTICEABLE",
                label_de="Nichts Auffälliges",
                label_en="Nothing noticeable",
                label_pl="Nic zauważalnego",
            ),
        ],
    ),
    _q(
        "Q104",
        path_code="CCE-006",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=6040,
        text_de="Welche Begleitsymptome treten auf?",
        text_en="What accompanying symptoms occur?",
        text_pl="Jakie objawy towarzyszą?",
        options=[
            _opt(
                "BURNING",
                label_de="Brennen",
                label_en="Burning",
                label_pl="Pieczenie",
            ),
            _opt("ITCHING", label_de="Jucken", label_en="Itching", label_pl="Świąd"),
            _opt("PAIN", label_de="Schmerz", label_en="Pain", label_pl="Ból"),
            _opt("SWELLING", label_de="Schwellung", label_en="Swelling", label_pl="Obrzęk"),
            _opt(
                "PIMPLES",
                label_de="Pickel/Knötchen",
                label_en="Pimples",
                label_pl="Krostki",
            ),
            _opt(
                "FLAKING",
                label_de="Schuppung",
                label_en="Flaking",
                label_pl="Łuszczenie",
            ),
            NONE,
        ],
    ),
    _q(
        "Q105",
        path_code="CCE-006",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=6050,
        text_de="Haben Sie Fieber?",
        text_en="Do you have a fever?",
        text_pl="Czy występuje gorączka?",
        options=YES_NO,
    ),
    _q(
        "Q106",
        path_code="CCE-006",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=6060,
        text_de="Ist die Rötung deutlich einseitig?",
        text_en="Is the redness clearly on one side only?",
        text_pl="Czy zaczerwienienie jest wyraźnie jednostronne?",
        options=YES_NO,
    ),
    _q(
        "Q107",
        path_code="CCE-006",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=6070,
        text_de="Haben Sie neue Kosmetika oder ästhetische Behandlungen verwendet?",
        text_en="Have you used new cosmetics or aesthetic treatments?",
        text_pl="Czy użyto nowych kosmetyków lub zabiegów estetycznych?",
        options=YES_NO,
    ),
    _ft(
        "Q107a",
        path_code="CCE-006",
        display_order=6075,
        text_de="Welche?",
        text_en="Which ones?",
        text_pl="Jakich?",
        show_if={"question_id": "Q107", "op": "eq", "value": "YES"},
    ),
    _q(
        "Q108",
        path_code="CCE-006",
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=6080,
        text_de="Hatten Sie früher schon ähnliche Episoden?",
        text_en="Have you had similar episodes before?",
        text_pl="Czy wcześniej występowały podobne epizody?",
        options=YES_NO,
    ),
]
