"""Seed data for telederm path CCE-003 (subcutaneous nodule)."""

from __future__ import annotations

from typing import Any

from apps.telederm.models import TeledermAnswerType, TeledermSection
from apps.telederm.seed.helpers import (
    NO,
    OTHER,
    UNKNOWN,
    YES_NO,
    YES_NO_UNKNOWN,
    _ft,
    _opt,
    _q,
)

PATH_CODE = "CCE-003"

CCE003_QUESTIONS: list[dict[str, Any]] = [
    _q(
        "Q040",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=3000,
        text_de="Wo befindet sich der Knoten / die Verdickung?",
        text_en="Where is the lump or thickening located?",
        text_pl="Gdzie znajduje się guzek / zgrubienie?",
        options=[
            _opt("FACE", label_de="Gesicht", label_en="Face", label_pl="Twarz"),
            _opt("NECK", label_de="Hals", label_en="Neck", label_pl="Szyja"),
            _opt("TRUNK", label_de="Rumpf", label_en="Trunk", label_pl="Tułów"),
            _opt("BACK", label_de="Rücken", label_en="Back", label_pl="Plecy"),
            _opt("AXILLA", label_de="Achsel", label_en="Armpit", label_pl="Pacha"),
            _opt("GROIN", label_de="Leiste", label_en="Groin", label_pl="Pachwina"),
            _opt(
                "UPPER_LIMB",
                label_de="Obere Extremität",
                label_en="Upper limb",
                label_pl="Kończyna górna",
            ),
            _opt(
                "LOWER_LIMB",
                label_de="Untere Extremität",
                label_en="Lower limb",
                label_pl="Kończyna dolna",
            ),
            OTHER,
        ],
    ),
    _q(
        "Q041",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=3010,
        text_de="Seit wann ist er vorhanden?",
        text_en="How long has it been present?",
        text_pl="Od kiedy jest obecny?",
        options=[
            _opt(
                "UNDER_SEVEN_DAYS",
                label_de="Weniger als 7 Tage",
                label_en="Less than 7 days",
                label_pl="Mniej niż 7 dni",
            ),
            _opt(
                "ONE_TO_FOUR_WEEKS",
                label_de="1–4 Wochen",
                label_en="1–4 weeks",
                label_pl="1–4 tygodnie",
            ),
            _opt(
                "ONE_TO_SIX_MONTHS",
                label_de="1–6 Monate",
                label_en="1–6 months",
                label_pl="1–6 miesięcy",
            ),
            _opt(
                "OVER_SIX_MONTHS",
                label_de="Länger als 6 Monate",
                label_en="More than 6 months",
                label_pl="Ponad 6 miesięcy",
            ),
            UNKNOWN,
        ],
    ),
    _q(
        "Q042",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=3020,
        text_de="Vergrößert sich der Knoten?",
        text_en="Is the lump enlarging?",
        text_pl="Czy guzek się powiększa?",
        options=[
            _opt(
                "YES_QUICKLY",
                label_de="Ja, schnell",
                label_en="Yes, quickly",
                label_pl="Tak, szybko",
            ),
            _opt(
                "YES_SLOWLY",
                label_de="Ja, langsam",
                label_en="Yes, slowly",
                label_pl="Tak, powoli",
            ),
            NO,
            UNKNOWN,
        ],
    ),
    _q(
        "Q043",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=3030,
        text_de="Tut er weh?",
        text_en="Does it hurt?",
        text_pl="Czy boli?",
        options=YES_NO,
    ),
    _q(
        "Q044",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.MULTIPLE,
        display_order=3040,
        text_de="Ist die Haut darüber gerötet oder wärmer?",
        text_en="Is the skin over it reddened or warmer?",
        text_pl="Czy skóra nad nim jest zaczerwieniona lub cieplejsza?",
        options=[
            _opt(
                "REDDENED",
                label_de="Gerötet",
                label_en="Reddened",
                label_pl="Zaczerwieniona",
            ),
            _opt(
                "WARMER",
                label_de="Wärmer",
                label_en="Warmer",
                label_pl="Cieplejsza",
            ),
            _opt("BOTH", label_de="Beides", label_en="Both", label_pl="Oba"),
            NO,
            UNKNOWN,
        ],
    ),
    _q(
        "Q045",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=3050,
        text_de="Tritt Ausfluss / Eiter auf?",
        text_en="Is there discharge or pus?",
        text_pl="Czy występuje wydzielina / ropa?",
        options=YES_NO,
    ),
    _q(
        "Q046",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=3060,
        text_de="Hatten Sie Fieber?",
        text_en="Have you had a fever?",
        text_pl="Czy wystąpiła gorączka?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q047",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=3070,
        text_de="Ist der Knoten nach Verletzung, Injektion oder Biss aufgetreten?",
        text_en="Did the lump appear after injury, injection, or a bite?",
        text_pl="Czy guzek pojawił się po urazie, zastrzyku lub ukąszeniu?",
        options=YES_NO_UNKNOWN,
    ),
    _q(
        "Q048",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=3080,
        text_de="Hatten Sie früher schon ein ähnliches Problem?",
        text_en="Have you had a similar problem before?",
        text_pl="Czy podobny problem występował wcześniej?",
        options=YES_NO,
    ),
    _q(
        "Q049",
        path_code=PATH_CODE,
        section=TeledermSection.QUESTIONNAIRE,
        answer_type=TeledermAnswerType.SINGLE,
        display_order=3090,
        text_de="Wurde er bereits beurteilt oder behandelt?",
        text_en="Has it already been assessed or treated?",
        text_pl="Czy był już oceniany lub leczony?",
        options=YES_NO,
    ),
    _ft(
        "Q049a",
        path_code=PATH_CODE,
        display_order=3095,
        text_de="Welche Behandlung wurde durchgeführt?",
        text_en="What treatment was applied?",
        text_pl="Jakie leczenie zastosowano?",
        show_if={"question_id": "Q049", "op": "eq", "value": "YES"},
    ),
]
