# Generated by Django 6.0.2 on 2026-02-28 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_admin_role_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='role',
            field=models.CharField(choices=[('RECEPTION', 'Reception'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin'), ('TABLET', 'Tablet (waiting room)')], default='RECEPTION', max_length=20),
        ),
    ]
