# Generated by Django 6.0.2 on 2026-03-03 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0013_dailyqueue_assigned_doctor_patient_clinic_sites'),
        ('users', '0004_alter_staffuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffuser',
            name='clinic_sites',
            field=models.ManyToManyField(blank=True, db_table='staff_user_clinic_site', related_name='staff_users', to='reception.clinicsite'),
        ),
    ]
