# Generated by Django 6.0.2 on 2026-03-04 18:33

from django.db import migrations

def create_groups_and_migrate_users(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    StaffUser = apps.get_model('users', 'StaffUser')

    doctor_group, _ = Group.objects.get_or_create(name='Doctor')
    reception_group, _ = Group.objects.get_or_create(name='Reception')
    admin_group, _ = Group.objects.get_or_create(name='Admin')
    tablet_group, _ = Group.objects.get_or_create(name='Tablet')

    # W miarę możliwości (jeśli uprawnienia już istnieją w bazie), przypiszmy je.
    admin_group.permissions.set(Permission.objects.all())

    doctor_perms = Permission.objects.filter(
        codename__in=[
            'view_patient', 'view_clinicsite', 'view_consultingroom', 'view_dailyqueue',
            'view_queueentry', 'view_patientcontacthistory', 'view_medicaldocument',
            'add_medicaldocument', 'change_medicaldocument', 'view_doctortexttemplate',
            'add_doctortexttemplate', 'change_doctortexttemplate', 'view_auditevent',
        ]
    )
    doctor_group.permissions.set(doctor_perms)

    reception_perms = Permission.objects.filter(
        codename__in=[
            'view_patient', 'add_patient', 'change_patient',
            'view_dailyqueue', 'add_dailyqueue', 'change_dailyqueue',
            'view_queueentry', 'add_queueentry', 'change_queueentry',
            'view_patientformsession', 'add_patientformsession', 'change_patientformsession',
            'view_patientimportbatch', 'add_patientimportbatch', 'view_patientimporterror',
            'view_clinicsite', 'view_consultingroom'
        ]
    )
    reception_group.permissions.set(reception_perms)

    # Migracja użytkowników
    ROLE_GROUP_MAP = {
        'DOCTOR': doctor_group,
        'RECEPTION': reception_group,
        'ADMIN': admin_group,
        'TABLET': tablet_group,
    }

    for user in StaffUser.objects.all():
        group = ROLE_GROUP_MAP.get(user.role)
        if group:
            user.groups.add(group)


def revert_groups_and_users(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name__in=['Doctor', 'Reception', 'Admin', 'Tablet']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_staffuser_clinic_sites'),
        ('auth', '0012_alter_user_first_name_max_length'), # Wymagamy auth, aby Group i Permission istniały
    ]

    operations = [
        migrations.RunPython(create_groups_and_migrate_users, revert_groups_and_users)
    ]
