# Generated by Django 6.0.2 on 2026-03-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_create_roles_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffuser',
            name='role',
        ),
    ]
