# Generated by Django 6.0.2 on 2026-03-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffuser',
            options={'verbose_name': 'Staff user', 'verbose_name_plural': 'Staff users'},
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='code',
            field=models.CharField(default='', max_length=50, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Is staff'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='preferred_locale',
            field=models.CharField(default='de-DE', max_length=10, verbose_name='Preferred locale'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
