# Generated by Django 6.0.2 on 2026-03-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_remove_patientcontacthistory_perm_from_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffuser",
            name="preferred_locale",
            field=models.CharField(
                choices=[
                    ("de-DE", "Deutsch (Deutschland)"),
                    ("en-GB", "English (United Kingdom)"),
                    ("pl-PL", "Polski (Polska)"),
                ],
                default="de-DE",
                max_length=10,
                verbose_name="Preferred locale",
            ),
        ),
    ]
