# Generated by Django 6.0.4 on 2026-04-15 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0035_alter_patientformsession_options_and_more'),
        ('users', '0011_staffuser_preferred_locale_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='clinic_sites',
            field=models.ManyToManyField(blank=True, db_table='staff_user_clinic_site', related_name='staff_users', to='reception.clinicsite', verbose_name='Clinic sites'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='consulting_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_users', to='reception.consultingroom', verbose_name='Consulting room'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='preferred_locale',
            field=models.CharField(choices=[('de-DE', 'German (Germany)'), ('en-GB', 'English (United Kingdom)'), ('pl-PL', 'Polish (Poland)')], default='de-DE', max_length=10, verbose_name='Preferred locale'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
