# Generated by Django 6.0.4 on 2026-04-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_staffuser_professional_title_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffuser",
            name="gender",
            field=models.CharField(
                choices=[
                    ("UNSPECIFIED", "Not specified"),
                    ("FEMALE", "Female"),
                    ("MALE", "Male"),
                ],
                default="UNSPECIFIED",
                help_text="Steuert die PDF-Signaturzeile „Facharzt / Fachärztin für Dermatologie“. Bei „Keine Angabe“ wird die männliche Form verwendet — für die korrekte weibliche Form bitte „Weiblich“ wählen.",
                max_length=20,
                verbose_name="Gender (PDF footer)",
            ),
        ),
    ]
