# Generated by Django 6.0.5 on 2026-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_staffuser_gender_help_text_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffuser',
            name='gender',
            field=models.CharField(choices=[('UNSPECIFIED', 'Not specified'), ('FEMALE', 'Female'), ('MALE', 'Male')], default='UNSPECIFIED', max_length=20, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='professional_title',
            field=models.CharField(blank=True, default='Dr. med.', max_length=80, verbose_name='Professional title'),
        ),
    ]
