# Generated by Django 4.2.4 on 2026-02-16 22:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorTextTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('template_locale', models.CharField(default='de-DE', max_length=10)),
                ('template_body', models.TextField()),
                ('is_global', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'doctor_text_template',
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('current_version_no', models.IntegerField(default=0)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medical_document',
            },
        ),
        migrations.CreateModel(
            name='MedicalDocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_no', models.IntegerField()),
                ('version_status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('publish_request_id', models.UUIDField(blank=True, null=True)),
                ('pdf_generation_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('medical_payload_schema_version', models.SmallIntegerField(default=1)),
                ('medical_payload', models.JSONField(default=dict)),
                ('diagnosis_code', models.CharField(blank=True, max_length=50, null=True)),
                ('procedure_code', models.CharField(blank=True, max_length=50, null=True)),
                ('pdf_local_path', models.CharField(blank=True, max_length=500, null=True)),
                ('pdf_checksum_sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('hidrive_path', models.CharField(blank=True, max_length=500, null=True)),
                ('hidrive_sent', models.BooleanField(default=False)),
                ('hidrive_sent_at', models.DateTimeField(blank=True, null=True)),
                ('sms_sent', models.BooleanField(default=False)),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True)),
                ('local_pdf_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='medical.medicaldocument')),
            ],
            options={
                'db_table': 'medical_document_version',
            },
        ),
    ]
