# Generated by Django 4.2.4 on 2026-02-16 22:44

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reception', '0001_initial'),
        ('intake', '0002_initial'),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocumentversion',
            name='publish_requested_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_medical_publications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaldocumentversion',
            name='published_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_medical_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_medical_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='intake_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='medical_document', to='intake.patientintakeform'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='queue_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='medical_document', to='reception.queueentry'),
        ),
        migrations.AddField(
            model_name='medicaldocument',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctortexttemplate',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='medicaldocumentversion',
            index=models.Index(fields=['medical_document', '-version_no'], name='medical_doc_medical_43aae4_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocumentversion',
            index=models.Index(fields=['version_status', '-published_at'], name='medical_doc_version_1dbe86_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocumentversion',
            index=models.Index(fields=['hidrive_sent', 'sms_sent', 'published_at'], name='medical_doc_hidrive_890104_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocumentversion',
            index=models.Index(condition=models.Q(('hidrive_sent', True), ('local_pdf_deleted_at__isnull', True), ('sms_sent', True), ('version_status', 'PUBLISHED')), fields=['published_at'], name='medical_document_retention_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocumentversion',
            index=django.contrib.postgres.indexes.GinIndex(fields=['medical_payload'], name='medical_payload_gin_idx', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddConstraint(
            model_name='medicaldocumentversion',
            constraint=models.UniqueConstraint(fields=('medical_document', 'version_no'), name='medical_document_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='medicaldocumentversion',
            constraint=models.UniqueConstraint(fields=('medical_document', 'publish_request_id'), name='medical_document_publish_request_unique'),
        ),
        migrations.AddConstraint(
            model_name='medicaldocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_no__gt', 0)), name='medical_document_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='medicaldocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_status', 'DRAFT'), ('publish_request_id__isnull', False), _connector='OR'), name='medical_document_published_requires_request_id'),
        ),
        migrations.AddConstraint(
            model_name='medicaldocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('version_status', 'DRAFT'), ('published_at__isnull', False), _connector='OR'), name='medical_document_published_requires_time'),
        ),
        migrations.AddConstraint(
            model_name='medicaldocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pdf_generation_status', 'COMPLETED'), ('pdf_local_path__isnull', False)), models.Q(('pdf_generation_status', 'COMPLETED'), _negated=True), _connector='OR'), name='medical_document_pdf_completed_requires_path'),
        ),
        migrations.AddConstraint(
            model_name='medicaldocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('hidrive_sent', False), models.Q(('hidrive_sent', True), ('hidrive_sent_at__isnull', False)), _connector='OR'), name='medical_document_hidrive_sent_requires_time'),
        ),
        migrations.AddConstraint(
            model_name='medicaldocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('sms_sent', False), models.Q(('sms_sent', True), ('sms_sent_at__isnull', False)), _connector='OR'), name='medical_document_sms_sent_requires_time'),
        ),
        migrations.AddConstraint(
            model_name='medicaldocumentversion',
            constraint=models.CheckConstraint(condition=models.Q(('local_pdf_deleted_at__isnull', True), models.Q(('hidrive_sent', True), ('sms_sent', True)), _connector='OR'), name='medical_document_local_pdf_deletion_guard'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['status', '-updated_at'], name='medical_doc_status_178e67_idx'),
        ),
        migrations.AddConstraint(
            model_name='medicaldocument',
            constraint=models.CheckConstraint(condition=models.Q(('current_version_no__gte', 0)), name='medical_document_current_version_non_negative'),
        ),
        migrations.AddIndex(
            model_name='doctortexttemplate',
            index=models.Index(fields=['owner_user', 'template_locale', 'is_active'], name='doctor_text_owner_u_f474fa_idx'),
        ),
        migrations.AddIndex(
            model_name='doctortexttemplate',
            index=models.Index(fields=['is_global', 'template_locale', 'is_active'], name='doctor_text_is_glob_42e0d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctortexttemplate',
            constraint=models.CheckConstraint(condition=models.Q(('template_locale__regex', '^(de|en)(-[A-Z]{2})?$')), name='doctor_template_locale_format'),
        ),
        migrations.AddConstraint(
            model_name='doctortexttemplate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_global', True), ('owner_user__isnull', True)), models.Q(('is_global', False), ('owner_user__isnull', False)), _connector='OR'), name='doctor_template_global_owner_consistency'),
        ),
        migrations.AddConstraint(
            model_name='doctortexttemplate',
            constraint=models.UniqueConstraint(fields=('owner_user', 'name', 'template_locale'), name='doctor_template_owner_name_locale_unique'),
        ),
    ]
