# Generated by Django 6.0.2 on 2026-03-03 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_published_requires_publish_locale'),
        ('reception', '0013_dailyqueue_assigned_doctor_patient_clinic_sites'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='doctortexttemplate',
            name='doctor_template_global_owner_consistency',
        ),
        migrations.AddField(
            model_name='doctortexttemplate',
            name='clinic_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_templates', to='reception.clinicsite'),
        ),
        migrations.AddIndex(
            model_name='doctortexttemplate',
            index=models.Index(fields=['clinic_site', 'template_locale', 'is_active'], name='doctor_text_clinic__f65a42_idx'),
        ),
        migrations.AddConstraint(
            model_name='doctortexttemplate',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('is_global', True), ('owner_user__isnull', True)), models.Q(('is_global', False), models.Q(models.Q(('owner_user__isnull', False), ('clinic_site__isnull', True)), models.Q(('owner_user__isnull', True), ('clinic_site__isnull', False)), _connector='OR')), _connector='OR'), name='doctor_template_global_owner_consistency'),
        ),
        migrations.AddConstraint(
            model_name='doctortexttemplate',
            constraint=models.UniqueConstraint(fields=('clinic_site', 'name', 'template_locale'), name='doctor_template_clinic_name_locale_unique'),
        ),
    ]
