# Generated by Django 6.0.2 on 2026-03-03 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0018_update_contact_method_prompt_multiselect'),
        ('medical', '0006_remove_doctortexttemplate_doctor_template_global_owner_consistency_and_more'),
        ('reception', '0015_dailyqueue_daily_queue_assigne_397070_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['created_by_user', '-created_at'], name='medical_doc_created_83fd44_idx'),
        ),
    ]
