# Generated by Django 6.0.2 on 2026-03-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0007_medicaldocument_medical_doc_created_83fd44_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctortexttemplate',
            options={'verbose_name': 'Doctor template', 'verbose_name_plural': 'Doctor templates'},
        ),
        migrations.AlterModelOptions(
            name='medicaldocument',
            options={'verbose_name': 'Medical document', 'verbose_name_plural': 'Medical documents'},
        ),
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='is_global',
            field=models.BooleanField(default=False, verbose_name='Is global'),
        ),
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='lesion_group_favorites',
            field=models.JSONField(blank=True, default=list, verbose_name='Lesion group favorites'),
        ),
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='summary_favorites',
            field=models.JSONField(blank=True, default=list, verbose_name='Summary favorites'),
        ),
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='template_body',
            field=models.TextField(verbose_name='Template body'),
        ),
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='template_locale',
            field=models.CharField(default='de-DE', max_length=10, verbose_name='Template locale'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='current_version_no',
            field=models.IntegerField(default=0, verbose_name='Current version no'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='last_published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last published at'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='diagnosis_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Diagnosis code'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='hidrive_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Hidrive path'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='hidrive_sent',
            field=models.BooleanField(default=False, verbose_name='Hidrive sent'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='hidrive_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hidrive sent at'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='local_pdf_deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Local pdf deleted at'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='medical_payload',
            field=models.JSONField(default=dict, verbose_name='Medical payload'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='medical_payload_schema_version',
            field=models.SmallIntegerField(default=1, verbose_name='Medical payload schema version'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='pdf_checksum_sha256',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Pdf checksum sha256'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='pdf_local_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Pdf local path'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='procedure_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Procedure code'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='publish_locale',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Publish locale'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published at'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='sms_sent',
            field=models.BooleanField(default=False, verbose_name='Sms sent'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sms sent at'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='version_no',
            field=models.IntegerField(verbose_name='Version no'),
        ),
    ]
