# Generated by Django 6.0.2 on 2026-03-14 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_remove_doctortexttemplate_summary_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocumentversion',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Revoked at'),
        ),
    ]
