# Generated by Django 6.0.2 on 2026-03-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_add_revoked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='publish_locale',
            field=models.CharField(blank=True, choices=[('de-DE', 'Deutsch (Deutschland)'), ('en-GB', 'English (United Kingdom)'), ('pl-PL', 'Polski (Polska)')], max_length=10, null=True, verbose_name='Publish locale'),
        ),
    ]
