# Generated by Django 6.0.2 on 2026-03-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_medical_document_version_publish_locale_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='template_locale',
            field=models.CharField(choices=[('de-DE', 'Deutsch (Deutschland)'), ('en-GB', 'English (United Kingdom)'), ('pl-PL', 'Polski (Polska)')], default='de-DE', max_length=10, verbose_name='Template locale'),
        ),
    ]
