# Generated by Django 6.0.4 on 2026-04-15 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0024_alter_anamnesisoptiondefinition_options_and_more'),
        ('medical', '0015_external_pdf_attachment'),
        ('reception', '0035_alter_patientformsession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalpdfattachment',
            options={'verbose_name': 'External PDF attachment', 'verbose_name_plural': 'External PDF attachments'},
        ),
        migrations.AlterModelOptions(
            name='medicaldocumentversion',
            options={'verbose_name': 'Medical document version', 'verbose_name_plural': 'Medical document versions'},
        ),
        migrations.RenameIndex(
            model_name='externalpdfattachment',
            new_name='external_pd_medical_aa6b12_idx',
            old_name='external_pdf_doc_status_idx',
        ),
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='clinic_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_templates', to='reception.clinicsite', verbose_name='Clinic site'),
        ),
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_templates', to=settings.AUTH_USER_MODEL, verbose_name='Owner user'),
        ),
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='template_locale',
            field=models.CharField(choices=[('de-DE', 'German (Germany)'), ('en-GB', 'English (United Kingdom)'), ('pl-PL', 'Polish (Poland)')], default='de-DE', max_length=10, verbose_name='Template locale'),
        ),
        migrations.AlterField(
            model_name='doctortexttemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='externalpdfattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='externalpdfattachment',
            name='hidrive_remote_path',
            field=models.CharField(max_length=500, verbose_name='HiDrive path'),
        ),
        migrations.AlterField(
            model_name='externalpdfattachment',
            name='medical_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_pdfs', to='medical.medicaldocument', verbose_name='Medical document'),
        ),
        migrations.AlterField(
            model_name='externalpdfattachment',
            name='original_filename',
            field=models.CharField(max_length=255, verbose_name='Original filename'),
        ),
        migrations.AlterField(
            model_name='externalpdfattachment',
            name='status',
            field=models.CharField(choices=[('MATCHED', 'Matched'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('MERGE_FAILED', 'Merge failed')], default='MATCHED', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='created_by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='created_medical_documents', to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='intake_form',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='medical_document', to='intake.patientintakeform', verbose_name='Intake form'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='queue_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='medical_document', to='reception.queueentry', verbose_name='Queue entry'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='updated_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medical_documents', to=settings.AUTH_USER_MODEL, verbose_name='Updated by'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='medical_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='medical.medicaldocument', verbose_name='Medical document'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='pdf_generation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='PDF generation status'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='publish_locale',
            field=models.CharField(blank=True, choices=[('de-DE', 'German (Germany)'), ('en-GB', 'English (United Kingdom)'), ('pl-PL', 'Polish (Poland)')], max_length=10, null=True, verbose_name='Publish locale'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='publish_request_id',
            field=models.UUIDField(blank=True, null=True, verbose_name='Publish request ID'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='publish_requested_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_medical_publications', to=settings.AUTH_USER_MODEL, verbose_name='Publish requested by'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='published_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_medical_documents', to=settings.AUTH_USER_MODEL, verbose_name='Published by'),
        ),
        migrations.AlterField(
            model_name='medicaldocumentversion',
            name='version_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20, verbose_name='Version status'),
        ),
    ]
