# Generated by Django 6.0.4 on 2026-04-30 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0025_patientintakeform_reopen_reception_note'),
        ('medical', '0017_medicaldocument_revision_state'),
        ('reception', '0037_drop_queue_entry_status_published'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldocument',
            name='source_type',
            field=models.CharField(choices=[('DIGITAL_INTAKE', 'Digital intake'), ('PAPER_INTAKE', 'Paper intake')], default='DIGITAL_INTAKE', max_length=32, verbose_name='Document source type'),
        ),
        migrations.AlterField(
            model_name='medicaldocument',
            name='intake_form',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='medical_document', to='intake.patientintakeform', verbose_name='Intake form'),
        ),
        migrations.AddConstraint(
            model_name='medicaldocument',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_type', 'DIGITAL_INTAKE'), ('intake_form__isnull', False)), models.Q(('source_type', 'PAPER_INTAKE'), ('intake_form__isnull', True)), _connector='OR'), name='medical_document_source_type_intake_consistency'),
        ),
    ]
