# Generated by Django 6.0.5 on 2026-05-14 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0021_alter_externalpdfattachment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalpdfattachment',
            name='status',
            field=models.CharField(choices=[('PENDING_UPLOAD', 'Pending upload'), ('MATCHED', 'Matched'), ('ACCEPTED', 'Processed'), ('REJECTED', 'Rejected'), ('MERGE_FAILED', 'Merge failed'), ('UPLOAD_FAILED', 'Upload failed')], default='MATCHED', max_length=20, verbose_name='Status'),
        ),
    ]
