# Generated by Django 4.2.4 on 2026-02-16 22:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(max_length=80)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'audit_event',
            },
        ),
    ]
