# Generated by Django 4.2.4 on 2026-02-16 22:44

from django.conf import settings
import django.contrib.postgres.indexes
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operations', '0001_initial'),
        ('outbox', '0001_initial'),
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='medical_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='medical.medicaldocument'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='outbox_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='outbox.outboxevent'),
        ),
        migrations.AddField(
            model_name='auditevent',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='reception.patient'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['-event_time'], name='audit_event_event_t_9a1961_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=django.contrib.postgres.indexes.GinIndex(fields=['metadata'], name='audit_metadata_gin_idx', opclasses=['jsonb_path_ops']),
        ),
        migrations.AddConstraint(
            model_name='auditevent',
            constraint=models.CheckConstraint(condition=models.Q(('metadata__isnull', False)), name='audit_event_metadata_not_null'),
        ),
    ]
