# Generated by Django 6.0.2 on 2026-03-03 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
        ('reception', '0013_dailyqueue_assigned_doctor_patient_clinic_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='context_clinic_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='reception.clinicsite'),
        ),
    ]
