# Generated by Django 6.0.2 on 2026-03-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auditevent_context_clinic_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditevent',
            name='event_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Event time'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(max_length=80, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='metadata',
            field=models.JSONField(default=dict, verbose_name='Metadata'),
        ),
    ]
