# Generated by Django 6.0.2 on 2026-03-10 21:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_remove_doctortexttemplate_summary_favorites'),
        ('operations', '0004_alter_auditevent_event_time_and_more'),
        ('outbox', '0003_alter_outboxevent_aggregate_type_and_more'),
        ('reception', '0019_clinicsite_pdf_import_config'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['patient_id', '-event_time'], name='audit_event_patient_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['medical_document_id', '-event_time'], name='audit_event_doc_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['context_clinic_site_id', '-event_time'], name='audit_event_clinic_time_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['outbox_event_id', '-event_time'], name='audit_event_outbox_time_idx'),
        ),
    ]
