# Generated by Django 6.0.4 on 2026-04-15 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0016_alter_externalpdfattachment_options_and_more'),
        ('operations', '0005_audit_event_composite_indexes'),
        ('outbox', '0004_alter_outboxevent_options_and_more'),
        ('reception', '0035_alter_patientformsession_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'verbose_name': 'Audit event', 'verbose_name_plural': 'Audit events'},
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL, verbose_name='Actor user'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='context_clinic_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='reception.clinicsite', verbose_name='Context clinic site'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='medical_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='medical.medicaldocument', verbose_name='Medical document'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='outbox_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='outbox.outboxevent', verbose_name='Outbox event'),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='reception.patient', verbose_name='Patient'),
        ),
    ]
